apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:yZLIQWwhYIiPEi0QO0EWhH76XicHbxJyqUUU5nSHFAJxiEmoI+ASXM3VemS5hP2oh/l6jKY=,iv:ohxmIU01y09nwB948trtRqcyjlOHbe5glnSvyYIdgvs=,tag:gYUNqagT7RphgFBhG8CvFQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGkyb2l6Y2dr
        S25pWkhLUTE5WVJFUHl2UkpPZnE1MUhlSC9RYVJ2YndISzdLaTBUeTY0SElSYWZV
        TnJpQ3lEQVlhNmlOZzNZM1VHa1ZvUmxLb2NlSzNjbzA0cFdnRHFEK0lSbjlSOU16
        Nzc0UXYrdCtPd1pJYm5yeFZuVEdGODNEbm85WXlpSnYzdzVLOFdZZ0E0bGptVXlq
        dnRWSTQ2MTkzL1FBZnBmWnlFeFU3ME9YV085cW5TWWVqWGo2TzFaL1lGQTEycDNQ
        SWh1SXY5T0k4dEhUZUdYTVY4Y2JyM1ZnL3ArZERUenNDa1FwWGs4bWQ5a21nZElU
        NERHM3hmaTVmelBpT0pIbjRHNGZZMGM1ZmRZYk52RUdrYjBWU0RiU0VMcjlONEdz
        a3JndzE0YnVpSVFxa0Q3dldNWHhqSUJIZTFXcHMrRCtQY2dqSnQ4RlZtUm5GdVAr
        NCtXZUdaZElSbER0dWEwbXgwc2RKTDcya3ViOXJZNjluSmF4SXpueHZzMHlYUFRI
        UjlJekUyQUxURHB1VWdLaWx5UWtvRzBCeERuNG0wcVUwN1RiRnhnSUxrRXJNQnNq
        YTlKRk5wRUgyL1grT2pSbHNyQkVDZjRnaXVvQW9BRmNsamZiTzY0a3o2NUh4enpZ
        dEMzM3lmTVFaZzZTQnM5bjBtYWI5cnNjVXplSzNjdE9MKzgyaTBsS3pnQ2pxemxw
        T3grZFpoYWRtSTJlckl3ZGxkVFZSYklOeW5FL3VHNzBHNGFJOEJXQ0oxN0I5QXZj
        MHZmNnFmZGdsZHM2SW81dFhPa2Rob01GN0R0eWpwSnFZaFRCK0hVZlFhOWJBT3BR
        UDRjRHhETDUrUUJnbitkYk92SlZpNnZpSCtMWUtoU014YUU1UmNNZzZPKzQrcDhz
        WVZPWXRvd2JGd3dkUmRJN2l1R0VISmFoeU54MHpoRkxwQTVhZTRJblhJNXF4Z2pR
        bzkzSE1Va3Z3NDBkanVONDA5Y1JjYW9YQzU0MmMwck4wTW5GS0RvR0RWT1d1akV4
        dXFvaDIxdEFrZTlibjR5SjRnU3I3aGlFYkFrcDRrcmxjZW1TYU4zcFdlaXhpT3o0
        SlBDMnBDNnBRK1I2Sy9rTFJXQUdETGwxdDl1a2k5QzUxUlJHT0t3UzdCMjZEVnIw
        ejM4U2UvYW5zWUlLUFg2MFpRQWRGL2hVWklkU2RTa2djZDRSSmVHRXN1YzU3SVdT
        aWY0Z1d0STdoU1FsanhNZmw1RmNlR0NsVWJqa0FaSFc1TWFaT0VpVzFORkVjTTEx
        dzkzVEhPR2pHQllLdnBWWGJQTnNrcWt4MnhQSVBxMFowSGpRakJzT01oZmRxeFNV
        aU1FV3dQN1F1RWJQZlIvR0Vab253cXFKTHVCenZueExYN1JnRnBSNFRmeUdiWUJh
        ano1akp0SjRZZXlwNTRMSFhQSnV1Vk94YkhHdDVuMmJBRkZVUzNCTXNGQnBoMjVj
        TWJvVVFPWUFhaXNJLy9rTDBQbGcvRzQvQ0R1dlFieWZwZDBYWFpsWnRHdmVKUElC
        RklIbzJYc0lPbDZTWWRRbWpPNml4MHpLY0FOalEzb2NCL3UvdisrVmZEMnpORUJS
        Rzh1TnhOVFJMckN4WUdabWRyODVnUWpjS09IeVY4ODlJcWVnNW16NG9WNkpJUXVu
        YVc4eFFnSTVhYzJMcjVTQ2JQVkF2QXNlSnAyVGQrbTJaaDk2dC9xMzI0b3QrWE44
        YzMrdnJLeDcwKytTQ1lKbm9EemIxaTNjalcvaGRncDJ1b002RXpaMDVJekF2UEJq
        d0lXZ212blBQTTFkWGw0RHg3ZDZDMlZiT3RaVlM2eDhlR1lTckNTYnl5cktvZi9v
        OWNuMFAwTFJYL2RwaVQrYUJvcGUrd1lRcUE0c2dnQ2d4SGVJNUVEZHRzR0dQMWV0
        cXdtLzJiQnFaRlM0d3hqa04rSVp5MWVTYzZDTFg5dTNpc1lkU1BtSFhXOVlGUQo5
        ZDJFNjJ2VHlPUW1DMU12NWM5WTNpanEyWWhCSXFvZDBEUXphamRMKytjCi0tLSBs
        MDZmbldRV2ROYVdmVVFtVWpKbXgxYW04dHJ1a0VTR3pBWk9ZUXlxUkNzCmka6Kje
        33dp6z7e1XRh00xnGDqcGRoHGqLIp4rfj0zRtV2d/ZVjOOHc++4nN9KQTqctDVXU
        t6baCbdcMenLirk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z2790e0enqwlpxt5q5mrgd59tx92fqfpeltynww0v46tmyd0jxup9x53j087q7vtc3zuhzdxp94hxthxnfd7rtdl2uz2d6jwwdueknvcfesczsmexd2cmgfet2ypxplsgxlzy6rgf3rzlx3907qrfl3sk4lexu4rs496hyms0vn5x624xycyqh08uj73kwq2vqxz5a6cpy02ssrtzfxwuzey5kuy4pzekrk2r92pvwmes2rgf8fnls4njw5hrx4a8x99tg58vm5j4zfux4a2vr9q0yaj72g2t4rhc0vv3g4z52842a782ppu50gyqwet0xsr9g2s8ny0zqjvmz5p9vp2wtnuexnkvg5tl4e9v3ep45gr6q0ryh03uvsvnz7dr4ftjmk42k2gwc22esyjvg4dg9uv6sx4cyjthwk7zx5y8aehnk9pvmn3yyygvx2d99vynvvra0gtal02y3axnfpxvxhsjg94sy58kld5yuggzw9s9j07gpj0au5utsv4c34yj6yp5pl3j4sc0g4z50ngp7xajxdjt9jytda3yc2un6qrrd3hvsypxag987e76tktgqqjfd23gwu0xzc6extlqv9faqa2vzn72m8xs9hvn6qhm9sxhpkmv65wwa4quu4jwnp6sf7vakavw4z2kgxp2j55glprp29j8v0uhyftsx30n3ejxd2g409zyt9xh4jnw2jc20qms4z6l4v3eflqnxqs8n5x3vc6dcv590kpnx36tythvsutuqfqqqxt8mjngcwfr34k22nw5fuhw7may4akketqplcu0vdd7xeetz2cyqe3mf4g4aktk36tzxmx2fu27s4ttrh4yd4g5szsj2wz5wtk8d3g47y9p6kaxzmwkgum74jwtqn929j4w4lhhxmx6pudcv340fskyxart475dpcl2ypw20qu59yz50c85da35qwstz7fnkqqm6g62qmc48v4wkj2jflpaqvt5g5ymuasxuyanjeqygryz6kvajajdgftdrxcv7aly2d08urxfaeg5rnz5gjcqgjmwkzzvw5x3uj5c5p64w98k86sz4m6us30py4tn0cxh6q9gcwxz4vuuzy32lmxr029qpmn2f0a4fzfq94edt96765s8fy0quq55zy0gu5yme9hxz5ze2rlga4fgkx0kpng2rgjj0yktfxf5pw5qq9vjf24twgm2vyg5zhk2gqu808q8ep5ne99xs9rjezutn6czxahqusscwypfs5n56ydcngq29dlg0p675qcmkpt062vccauw6dudhr0522q9lahhyz5jmlt5guq8sm7g6c5u2pmtu6502umzxfk0fd06g95zrqhgjf8e2gvwcx8q5ty4ds4phhkff6ek9xs7xxp4aqtlc9rghmjjv3tpvgxv2cq5eyj7smgjfkt2kh3gsuemd0r7ptkpypvrg8ekk9vyu2uxczsj9rw2h689s3vnpuhymqs7kztpxqchdyut5fmk9sjwrzghwhwauwr9ckf8qkp4mh2f9kfgw7jhfmawwynx7gsduts38chvgca4cg0uusnequvrsn92zw7ky0m8ycmmgu88g8velvkp8xl3w2n8ds6vkqutnyffqxf09snuehvff4wzxn4h2q5empzg6akyvm4y62geavzppkv9q2m2xmj42dea39ydpngxhch4e4vn0eu7kx0dwevzc5kx9djj6yfvs8cspgj07qp9wyqytw6852cg0e3qs43rqyraacj4gvvxavdwrhlg223xjck2muhz4q94uwh2qzdyku2xfy6gncj47xf4ypswpunv4gdj5ar63rvv5ksy3ngwkukz4kyve8pp6v52wk6tchx4jwjy0yzkwv83gz9xcuuq437e7vd4m2sgz3phpk9yjq57e7j56ksznjgrmadzz82xef48r2k548d52zgqkk8psu5pcjj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T05:54:05Z"
  mac: ENC[AES256_GCM,data:xdIfj+ZczErS4Uk1fQOnMAMMT3qZmsl9jaggfEsFRySkGDPsn/7F6sHRWTaCaKm+8UXcGrnF5jwEin1NUFo131ZW78rI8z3r9Bb74cJVKL1ZKXKgEdpJOwgzW7wFWz1TfK5wlumhdMJFBOECeyY6KjweofCaT5Eegn+4p5tuxKo=,iv:78j/soU5slZFeaK0dnQp9NXi5/GaqzPQ6VHF3br6erM=,tag:2r1OyOQJHqKZ748lxP6ddQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
