apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:7C469EhqFtrZkEzGmihZInRuSOmGtGk1hg0uIf+p5V8RalFRn+Hm1bEMTD3WRIVD3NmR84c=,iv:qRntuyz6GcBXqLS2oMNR54cNSWyX91BMH7siY758WpU=,tag:dBSGqirQ7x30tTScrvC5TQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFEvamlRbGJt
        SERMdzF4bllPVm5WS2MrOGVSNk4zT2FHSEJ1bUIwZEJ3T3dvUGtUQ2Y5M2F5elhY
        YTQvWDV1c04rUUYzaCtieUc4RmhpV3dZSm1pNkdFWjhOc1BuY0tvM1ZFNkFqeDVV
        dzRTQ3JzWFQ3MXJvZlBxdXVQY3krOTF6NmF4T084SmVqRVAvT0VEOUY1OURlT294
        aFV4ZlBSWCtZZ1NOYTEzbWlZWnZkSG5PUzdxQkZ6Q05EYkV4NFJmaGQvQ200OVM3
        TEl0QnQzRE1lUktVeGVDR0lqL3VyWGVnSFJQa05iUkJGUkdkeWVEakREamxYSngw
        TFFNT0pxQVZoU2RqTXY1YVBxU1NBbk90OStOK2hqR1gwdUh4M2d2bEZBbEZ3WndO
        WTNNYVQ2dnZIVEptWE5GTERpK1BDakV5QitKd1pZMHdlVXpmdUIyN1VlY1dWdGg4
        R0xvcVgzeG1LaW5HQ2VldmdwSDhCVkZRejQ0ejdKaHIyUnpsVEM2SUhjdnI3MjVH
        aThsMDdFWEJwb2I0dTBkd1BLd0xTcFV3QytBVjhWNlVpTUkweHhJc2VtZlY5NW5U
        b21QS1p4SytTUUF6Qm5HL2lNQkJoc1ozWU5mR3ZqaGJBak9rUFdIQ0RsQTk3blFL
        K1FxbVFxWHJybHdFRFo2OGF1ZVI2dXM5Z3R1S1Rja2hxVzZBRGUvKzNMUU5hYTEx
        TWhMY3V2NWhXUHJoNFJsVzRTRGFmTkI3cDJKYVp6WVdlRkQ3RFg4WmRpNmEydXRX
        LytaN3FmanB1b3FyQTZRSTlsczNMSWcwSzNTWjdPZmdWTFpNdDdwMGZuL1JDak1V
        T1RVUmdKN3ZKWnJxRXZHcWNnZURiN0hIbUg0aGJDRVU2NTFWNTdYbVh4SUtGem54
        NEVaYVF4ZG1XYzZFSEttUUJnUHR3VlJNcjY3bzMrY0psOEd3OXFEMWlsNFJNa3hB
        NG1YVGhybzNOdVJqeERSOENNa24wVkFOL1BobVY3VHNlWVFVSFdZZTBXTnlWRllP
        T2dUUU00TWZlaVlnZzU0clNPN01rckRtRGQrbFJSVEpPQkFjRUlJV2d4QjA0YjNu
        STl3bzRSOE5xcnBYZmQxUHpMbUozTEN0dkRiVWdpRTg4OGdyNGp6Sm5oQzlScEJC
        MW5YMFpBdDQvdG9kYlZ1dlVEbitzVlcrenRUUGVzWWlGb3Q2NFZMZDVRMll4RmtC
        SkE0NU41cEJGZm5NSzd6ZFlWSStjT25WaGRHeVdTQUF2N2lFMUw1bnRKS3Fwc25H
        VWZ6MUJwSUVRQnQ4MUVVL2duTXRiN08vbjg5THZRVDNSOHpETjkrdjRVZWNoa3p2
        YzF0RUpVa0JHZ0RIT2FHL3NORU5mdGtReWFmT3MxMENpVG5jN1MzekJQVGVjUDJl
        NllWUVY2akU1VjdHN0xzR0tsMzRJeFBONkhtOUVsTy9vc3RRQmxxRkZFV0Jnak8r
        N0E2SjNYdVpydUVuL3RMTm5jRU1tQTZGaVkxZTBkM1p3T0ZYdjUyUXFiQi9DdTRN
        blNDbFVONXNxYzErWXRPenRlcjBhU0kyMzlEWW0vRWd3ckZoOTB6M0UveDNoZ010
        ZFRQUVhodkxiYVVPUFpRZXROUTFuUWNrVCtwVyttOWpuR0g1elIyUW9RZGJrZWpa
        UGJLcmNFZGRtMDJ6cUZGVWdOaWJTbDJTa2d6Z21LdTM5bkVYQnF2SVlIUlVWQStN
        a0U3eWhONEd1UlE3eWtTbHlEcTRod3pwYVp0emhUZGdKYzd5bjBCTU5XZjNOVng4
        MERQWHhjOHJ6UUc0ZUc3cmRwZ0FqVE5OdUx3SVRVMGVmUUZDbTdWay9OaEtPN0c5
        WE51eGY1Rzg3c1hLZmczS3lDVXJjNEp5NGo3b2N6YldhMHpncSt5UXRuclcybEVV
        b3AxTVNheHZNbE0raEdKZktVMEp2dG5sakVIcGRRTU5TQmlzOTBGOGdLalBVUQpy
        ejFmUWlCUG82VlhaTlR6RE12Ty9saDU3R0N4OTdPZDNFdVNhSXhUMzRjCi0tLSB2
        T1E5bVJ0ald2akNzUnhNZ05YeGljaFUyZmp6QWtPQ2Rna1FRRlpUc0RBCkd/UcIA
        kofIgzX4aC6HzP6aa3OTCb79+YgxP0zDpumYyJo16DuZWZ46sT96bKWOHs50zO2u
        Jw2o75CRhyai7H8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z2790e0enqwlpxt5q5mrgd59tx92fqfpeltynww0v46tmyd0jxup9x53j087q7vtc3zuhzdxp94hxthxnfd7rtdl2uz2d6jwwdueknvcfesczsmexd2cmgfet2ypxplsgxlzy6rgf3rzlx3907qrfl3sk4lexu4rs496hyms0vn5x624xycyqh08uj73kwq2vqxz5a6cpy02ssrtzfxwuzey5kuy4pzekrk2r92pvwmes2rgf8fnls4njw5hrx4a8x99tg58vm5j4zfux4a2vr9q0yaj72g2t4rhc0vv3g4z52842a782ppu50gyqwet0xsr9g2s8ny0zqjvmz5p9vp2wtnuexnkvg5tl4e9v3ep45gr6q0ryh03uvsvnz7dr4ftjmk42k2gwc22esyjvg4dg9uv6sx4cyjthwk7zx5y8aehnk9pvmn3yyygvx2d99vynvvra0gtal02y3axnfpxvxhsjg94sy58kld5yuggzw9s9j07gpj0au5utsv4c34yj6yp5pl3j4sc0g4z50ngp7xajxdjt9jytda3yc2un6qrrd3hvsypxag987e76tktgqqjfd23gwu0xzc6extlqv9faqa2vzn72m8xs9hvn6qhm9sxhpkmv65wwa4quu4jwnp6sf7vakavw4z2kgxp2j55glprp29j8v0uhyftsx30n3ejxd2g409zyt9xh4jnw2jc20qms4z6l4v3eflqnxqs8n5x3vc6dcv590kpnx36tythvsutuqfqqqxt8mjngcwfr34k22nw5fuhw7may4akketqplcu0vdd7xeetz2cyqe3mf4g4aktk36tzxmx2fu27s4ttrh4yd4g5szsj2wz5wtk8d3g47y9p6kaxzmwkgum74jwtqn929j4w4lhhxmx6pudcv340fskyxart475dpcl2ypw20qu59yz50c85da35qwstz7fnkqqm6g62qmc48v4wkj2jflpaqvt5g5ymuasxuyanjeqygryz6kvajajdgftdrxcv7aly2d08urxfaeg5rnz5gjcqgjmwkzzvw5x3uj5c5p64w98k86sz4m6us30py4tn0cxh6q9gcwxz4vuuzy32lmxr029qpmn2f0a4fzfq94edt96765s8fy0quq55zy0gu5yme9hxz5ze2rlga4fgkx0kpng2rgjj0yktfxf5pw5qq9vjf24twgm2vyg5zhk2gqu808q8ep5ne99xs9rjezutn6czxahqusscwypfs5n56ydcngq29dlg0p675qcmkpt062vccauw6dudhr0522q9lahhyz5jmlt5guq8sm7g6c5u2pmtu6502umzxfk0fd06g95zrqhgjf8e2gvwcx8q5ty4ds4phhkff6ek9xs7xxp4aqtlc9rghmjjv3tpvgxv2cq5eyj7smgjfkt2kh3gsuemd0r7ptkpypvrg8ekk9vyu2uxczsj9rw2h689s3vnpuhymqs7kztpxqchdyut5fmk9sjwrzghwhwauwr9ckf8qkp4mh2f9kfgw7jhfmawwynx7gsduts38chvgca4cg0uusnequvrsn92zw7ky0m8ycmmgu88g8velvkp8xl3w2n8ds6vkqutnyffqxf09snuehvff4wzxn4h2q5empzg6akyvm4y62geavzppkv9q2m2xmj42dea39ydpngxhch4e4vn0eu7kx0dwevzc5kx9djj6yfvs8cspgj07qp9wyqytw6852cg0e3qs43rqyraacj4gvvxavdwrhlg223xjck2muhz4q94uwh2qzdyku2xfy6gncj47xf4ypswpunv4gdj5ar63rvv5ksy3ngwkukz4kyve8pp6v52wk6tchx4jwjy0yzkwv83gz9xcuuq437e7vd4m2sgz3phpk9yjq57e7j56ksznjgrmadzz82xef48r2k548d52zgqkk8psu5pcjj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T05:42:02Z"
  mac: ENC[AES256_GCM,data:4QuYjKwXA5GLecBOLP9c8nBc0xAdV55n5nJdnhro4WUAEqxxq9bHrcWYBOjzbmbxaz20TmQF8Qyf2tqcDK5hK9q3mSV2mcWuhSKuakoD4Q0j2DC8I6fQWNIlP6uSDhvTso5XtJNUu/zTc5qxBnx61numDlrqv/Ua2+Y+Eamsd0A=,iv:YizQ8Xp9F7EItIwcRpfcgshyjl/2lGvjDesEVrlv1HM=,tag:U2d1MCHXW8j0npQIJA/otw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
