apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:W5AHIamYhNj4mtY+0OY=,iv:kBngWW8O2NDHOsFyd/2n7cY25Q8uuYastx40szFSzgE=,tag:Fdogyur/MbJZR0RSsRb+tA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEliMGZyZkw0
        WVZOTTNOQmczTVFITTBZN2RUVDR0ZlFzYVlHRW12Z1J0WVFMYXVCMG12bGpDTzZa
        ZjFLUTFtUGN1M3Jyd0hsMzdtRVlTVytoUUFFSFJpRTFZVE9mbE5lU1NienlVSE4x
        U3NSVnZGczl2U0ZPckJoQlk2Zkx6UGFXbHhuTDN0L0VqNVUrSDM4NDZoL0lobU1s
        QjR4cllXWjdLV2hnTkgxcWExc1lmWmFrZDltNlF6ZEVkTUFDSkF3aGZWaGJMYytn
        TkZOdHhmeTJoYXc5RkN4czEycDROUHJyL3R5MmxNWGgwREJLMFNoNGpOOFQ5T285
        NklKMkxmVDJ2Mm1ITkZBRmpQTGxPT2lZNER5c0dVOTRCcHBRMHN3dGtZa0VETVEv
        Lzg1NmhkQWdYOVRaSENSTURqczR2TGlGRFJ6cGdUM2NMd0RrWDBTTzdFZUI4QTNm
        VlpoRHdJUW0wSDBEZzZLcWMrYWxzQjZvWE9USjVSUVJuSGZkNUQxdEMxbTlvZExY
        VnF4d3JkNGFDVWhBN1YvRTNqRXUxTUhCRnZpLzFORHFCcjVEWWdVZEI5SHNrellj
        MU5GUTVqZHRFOVhBS3BaWWFuK0M2bGhPYXBPYzJXOUc4MjlHR2FvVUtrNGd1UVI5
        d0diYll4Y3l4T2EvK3FOdWZqN2dpbW1lVmtIaVVyd1hQZHJmb1pod3BhUjdTbXd6
        T3lzZEE3NGJCck9UZHpFMWNFN1FRbnk0c1ZKVkE5YklHOGhrQzdUNlFaOWpueWF1
        UWxIMHRNUTBJUlhrdm1EUjgwTVJ1WXNkR01HYkY5bG9iMFZRU0d6WWgzSmJXd0d2
        ZC9ibEdaQUliSDhxWDk4Z2ozMEZsY1NIV29oREk5eTFTa1NoZDVUQkExSjJjRDg2
        TWpaVklZU2x4Wld0ODI5enEyekFpK3FnYkdSbUFiVzRzZHhGTmdtcXNmbHBqNmpJ
        VEFzUE5qSkZrVDNncjRrUHp6Wkpma2NnTzlrSTJaMzdURTBsdi9HVjQwZ0NZbWpX
        QmVMZGhlUXBNcmx1b0lWdmlIb0dPTzJNT0VmbG9nTjJTbk9jV1FLb1VoQldDOS9L
        alRrVFdpeCtKOTZsR3JtYmljUnA5eUNvYVY2dVZYMVl5Q0lnVUtVd2NJRHgza2V3
        M2xTT1FyL3lmTzc3NmVrajFZOGkwbXhJS1B6N3lJekhqTGhncFczMzF0SjBjTnRE
        U0l4UEhsOVRZdWkrUzdhSFJwaUNQUVFGeXpEYU9KcjZMcjdYeFl4ZEFmWWtCOUZt
        Mld6amlVV05OeUUydzg1OVZrWDFyRTFZTTRJKzFRK0lPYmxEa2wzTnR2M3M5dVZr
        ZFZTaVJUd3dZVWxQYll0NStUV3oxV2d2emlWSDZXdWIrM29LWXBzek5ySGx6N29s
        UlFsbE15RzFIdmNXdDllKzcyNFJYUWx2bitvZjRSMnprS21PMEdsQXU2T3FYWVdv
        Zkh6SFNoejFPSFdpQUpyQ1pndllBaFVkWkZoSkpqYjNtNUFGUzJKc3BoakdYbEpU
        bUJscmp2dUJrSVFrVWh1OWhQZzR2c3VDR0ltQ1N2TEFtb2ovT2VFd0trc1EyU3o2
        bDNFWkJlY2VtSUp0WFFvNkEzMWtHb3VrcG43cTFYa2doTVY5WFNrT25BZk1KbWFk
        SEV1UGV4cFFqMmc0WjlBVGVDLzAzZUFPeUpOTTdsK2ZLdlNCZ1hWb1FJdjF4Q20x
        bEJaMy9BdFVBUlZ2RlpvWVJEM2ptMzAwREIwY0Z5ZUxOTjdyTEpzNDNEM1p0dGMr
        OUl0MktXQkhpMUx0anRXalVzNUs2UEJCa2ZpTnZDUDlyYmtuSEYrd1lhRVpWeHF2
        cnQxWk9VMUNLZkdIQkE3dUM3Rlc1dnVJZEJ0cnNnWmpYaUdtM2Q1OVNRVlEzU0x4
        R1FQalpXRjdNSUdKT3kzbUVRQmd6bU5FSGt2dU83N3pycVc1c3FNbkxDVDhIZwpw
        M3A4QWRYRjc2Q0VJckcwZkdiTjZIUHhrUXBwZXN2Vm03aHVPa1RxUHlrCi0tLSBB
        WHlZRWlxWVVzNDIvOG0rUUVaTk1mcTI3RFgzVmRoaUFnNm5tUnFVdCtVCl565lv/
        LveU2LZZJOLDEsb/ECA+L1hMlTsYGoBX6PGnxfT2P4T64UiQplYKHIhjVA1mpFaj
        9FUh8G4c09o1h3g=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z2790e0enqwlpxt5q5mrgd59tx92fqfpeltynww0v46tmyd0jxup9x53j087q7vtc3zuhzdxp94hxthxnfd7rtdl2uz2d6jwwdueknvcfesczsmexd2cmgfet2ypxplsgxlzy6rgf3rzlx3907qrfl3sk4lexu4rs496hyms0vn5x624xycyqh08uj73kwq2vqxz5a6cpy02ssrtzfxwuzey5kuy4pzekrk2r92pvwmes2rgf8fnls4njw5hrx4a8x99tg58vm5j4zfux4a2vr9q0yaj72g2t4rhc0vv3g4z52842a782ppu50gyqwet0xsr9g2s8ny0zqjvmz5p9vp2wtnuexnkvg5tl4e9v3ep45gr6q0ryh03uvsvnz7dr4ftjmk42k2gwc22esyjvg4dg9uv6sx4cyjthwk7zx5y8aehnk9pvmn3yyygvx2d99vynvvra0gtal02y3axnfpxvxhsjg94sy58kld5yuggzw9s9j07gpj0au5utsv4c34yj6yp5pl3j4sc0g4z50ngp7xajxdjt9jytda3yc2un6qrrd3hvsypxag987e76tktgqqjfd23gwu0xzc6extlqv9faqa2vzn72m8xs9hvn6qhm9sxhpkmv65wwa4quu4jwnp6sf7vakavw4z2kgxp2j55glprp29j8v0uhyftsx30n3ejxd2g409zyt9xh4jnw2jc20qms4z6l4v3eflqnxqs8n5x3vc6dcv590kpnx36tythvsutuqfqqqxt8mjngcwfr34k22nw5fuhw7may4akketqplcu0vdd7xeetz2cyqe3mf4g4aktk36tzxmx2fu27s4ttrh4yd4g5szsj2wz5wtk8d3g47y9p6kaxzmwkgum74jwtqn929j4w4lhhxmx6pudcv340fskyxart475dpcl2ypw20qu59yz50c85da35qwstz7fnkqqm6g62qmc48v4wkj2jflpaqvt5g5ymuasxuyanjeqygryz6kvajajdgftdrxcv7aly2d08urxfaeg5rnz5gjcqgjmwkzzvw5x3uj5c5p64w98k86sz4m6us30py4tn0cxh6q9gcwxz4vuuzy32lmxr029qpmn2f0a4fzfq94edt96765s8fy0quq55zy0gu5yme9hxz5ze2rlga4fgkx0kpng2rgjj0yktfxf5pw5qq9vjf24twgm2vyg5zhk2gqu808q8ep5ne99xs9rjezutn6czxahqusscwypfs5n56ydcngq29dlg0p675qcmkpt062vccauw6dudhr0522q9lahhyz5jmlt5guq8sm7g6c5u2pmtu6502umzxfk0fd06g95zrqhgjf8e2gvwcx8q5ty4ds4phhkff6ek9xs7xxp4aqtlc9rghmjjv3tpvgxv2cq5eyj7smgjfkt2kh3gsuemd0r7ptkpypvrg8ekk9vyu2uxczsj9rw2h689s3vnpuhymqs7kztpxqchdyut5fmk9sjwrzghwhwauwr9ckf8qkp4mh2f9kfgw7jhfmawwynx7gsduts38chvgca4cg0uusnequvrsn92zw7ky0m8ycmmgu88g8velvkp8xl3w2n8ds6vkqutnyffqxf09snuehvff4wzxn4h2q5empzg6akyvm4y62geavzppkv9q2m2xmj42dea39ydpngxhch4e4vn0eu7kx0dwevzc5kx9djj6yfvs8cspgj07qp9wyqytw6852cg0e3qs43rqyraacj4gvvxavdwrhlg223xjck2muhz4q94uwh2qzdyku2xfy6gncj47xf4ypswpunv4gdj5ar63rvv5ksy3ngwkukz4kyve8pp6v52wk6tchx4jwjy0yzkwv83gz9xcuuq437e7vd4m2sgz3phpk9yjq57e7j56ksznjgrmadzz82xef48r2k548d52zgqkk8psu5pcjj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T05:54:05Z"
  mac: ENC[AES256_GCM,data:pFrV1MR3K27fDxW5A5PQ+H+JYkw+IgPPfcGidixkrZYCNF0UxhdDP52WLAdc4v1XAGgBFQsG4iVoReWkw6OAHkNFLA2j6ry5WEKoLGrVSJvXjDCVZsQH0dKHntbNfPivTT3wq78vvtwK1bM17G48y4f1F3bCkWpfhS86BxfZIhU=,iv:+DeogvHxHhDrfjArE9wOZg/MChs0AULO2shnTmUNg/w=,tag:nSODjw6QmB2T1hwopzRUHg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
