apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:h8UMor1bIbhQhxWMGVKYYcKNBNPmP41RsxhMlF48TxM=,iv:YuguvS6pps0XH6knkHXcO2p9Sq5DXndOIfNNiniO05U=,tag:IGjzQY8YDfmlQEvAKtMabQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG52allmb2E0
        TVVwcXJGNDRrNVJLbEN0clVrcHZPaDVaSmdUQldaaTBhZi9GbFUvK0czNjJIQ2Ji
        ZXFUdXNCYVJzcGdhc0RrN2RHSXUvL1paczdTRm52UmF0MElKUDM1MDBFZ1pXMUxu
        YWpWV2VOazFyelRmZDRnR0k5U2J6d2xFZWdPeWp0dHlhamZiVStMcnBXVDVNaE9E
        L3o3eTJaNVorWUtJRGN0bUFLa3dmdDRtejBCMDFNOUd3TnBZZW92dEYyQ0ljVmk5
        aWU2c0M4WjdxTWQ0TlNFNVpyZWEyczZpMjNvQUV4ZWthdW9YNWJNVk5FeDhkSy8y
        NXRHUHVKUnZYb3c0M2hIbmJiM3BtaWoyV25GbmhOc1VQVVNpWDYvVkU2OFJPakti
        R0RqaDFTUUQyajJaWUowK280YXJHSXJOVU1qRmhtQUlhWjNLTEhxeVdsNklFcDFm
        R1kxVURaOVc4MjJja2JvblNqVVFDVkF5T3lZcFpBZlhFMWxGOTZwR1ZTTk1qakFj
        ZU9jN0szRG5JMWhkOFQ1YkQxbWx2bnNwVitJbEhudVJrUkF2WkRlelI3d2xhUlZZ
        Um50NVB1UGpYNkJKSWYveEVvb1ZZeTB4WDRuazRMR3kySFA2Sk44UVNqUnBRU3hC
        YUp2QVpJWHRUYXBFUnFBUVJkVkI2NG9WUmpUK1RXLzRHZ21lMUFpdWJ0UGpPSyt2
        SkV4RVdsRXBNZHFqdmoyVHpXT0dXeEJWRG51ZVVER0ZCaVNaNkcrTEViREI0QWh6
        YkViMGM3UFVnd0Zkd09vZGxmbElybC9qV0pJTGgxVlV2N0lQYXp0K2toNDRjcnVD
        QmpSdUx6MXIxR0MyL0JIMkdHWjVIOUFkWlFPdWQ2QmkzS1JPd2pCT3dZK1JmTmY1
        RlZqTVRsdWEwMWx1MlR4L2Nad0w4d2xIRVFRTG5oT0FPTTV2eDBtM0xrRjZTVER0
        THdlbUdCdE1JSTg2eUNiaHk5QitUZmNDZTgzUlpVTm1DY0RJckdORG9leDdWK3lI
        UVdPRWhHT21KaUQvek9Ha29idEkybVh2N3o1UVQ1eDlnNTVmVEs1bU1aWkV1RG9J
        RHVJd3lqWXhsVmI3dHJmVzNyZ3ZGa2FjUXBZSzlYM2xsL2prNTF6Z2RDVGlaZ1hE
        VXR3SVhVQzlURngzV1BzWUgycDErOVd5ZG94SXJuL3NBOEVFUjllNnFhbFFRdEYy
        SUt1WXo4QzFBdUxzc1VGd214MHBVNkFCdzZDVkVHek5aRUlkUHV0WjhWeXk3Wlhp
        eUNGOXNYNkV1QjBvdkZOL3NyUWxNaWdtZHlueWtOelZKcUw4WFpOV3dDeFZoL2dp
        N0lRVStSTmxLWmVvYy9UdkZFM3U3cDlvRkRidFJvbVU1U1lHd0M2eHlWSVphRGx1
        WnZFUDZxRHBFTjVNejhQT05ZVjR4ayswaXN4ZVVVNjE3WUovNFJIOHRMRmFYTTl0
        YjdtbnRyb1RpMVoxT0hBbHBrRDl2Wk90UytKZW8xZTJMeU9wcDBpMXN5RjRISGpM
        WTB2R1dzRU0reDlOdTFtRk14NkFobXlXU0ZWNDdJK0NmRXhJak0zR0RxdXFqcjJY
        Y1dlVDViSElLUHZnOWo5QmJmZksrQlNGRXFHZmFiK2xkbDd3d1RTTEl0eHBnR3px
        dnhKY0EvMzNqcGJuLzl6a01WUi93ZXBFUEZqcHFhaWdZSTdrQXIweHEyS0xrWHpu
        RkpLOVd2bGtvT0JmVUEycGpnVHlzYUJMdm5NTjhwQ1oxZmI1Rnowd3FEbjR2R29G
        ZFBoSDlyMDZLM2M0czFjVTcyK1lnSnB3VDlQQXBaRzhyNFhmRDhqZ1ZRbGhGRnBF
        MWg4L1hKeHNFbGVtQ0ZWRlAyeEQwZXNnRlpDeXJMZkRBc0Mxb3ZyNzVJRGZkUGxy
        djBZWCthQlJ3UDhSVUtSU3RsOXI4L1E4VVFEdHA4d1p5bjUyZS9kd3lZZTZlQQox
        TjhocFF2Nk1YK09vMnRlaGo4YTZjckJEakZDSTFINEdVdGpMcGlQOEJBCi0tLSBG
        NEpKdTlGREZEUHFqMmxpUnpzb1hPaTkwUzNyODdKSitiRDFuWG9ZN3BzCpmJY+Bh
        M+Xy+UwTyL1TOJOmLxNUQunfVZwPTR+aGmSQ6IIRFIkmT5TjvG0ToGEakZRAch/e
        Xx6ZSS2oiZpGT0M=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z2790e0enqwlpxt5q5mrgd59tx92fqfpeltynww0v46tmyd0jxup9x53j087q7vtc3zuhzdxp94hxthxnfd7rtdl2uz2d6jwwdueknvcfesczsmexd2cmgfet2ypxplsgxlzy6rgf3rzlx3907qrfl3sk4lexu4rs496hyms0vn5x624xycyqh08uj73kwq2vqxz5a6cpy02ssrtzfxwuzey5kuy4pzekrk2r92pvwmes2rgf8fnls4njw5hrx4a8x99tg58vm5j4zfux4a2vr9q0yaj72g2t4rhc0vv3g4z52842a782ppu50gyqwet0xsr9g2s8ny0zqjvmz5p9vp2wtnuexnkvg5tl4e9v3ep45gr6q0ryh03uvsvnz7dr4ftjmk42k2gwc22esyjvg4dg9uv6sx4cyjthwk7zx5y8aehnk9pvmn3yyygvx2d99vynvvra0gtal02y3axnfpxvxhsjg94sy58kld5yuggzw9s9j07gpj0au5utsv4c34yj6yp5pl3j4sc0g4z50ngp7xajxdjt9jytda3yc2un6qrrd3hvsypxag987e76tktgqqjfd23gwu0xzc6extlqv9faqa2vzn72m8xs9hvn6qhm9sxhpkmv65wwa4quu4jwnp6sf7vakavw4z2kgxp2j55glprp29j8v0uhyftsx30n3ejxd2g409zyt9xh4jnw2jc20qms4z6l4v3eflqnxqs8n5x3vc6dcv590kpnx36tythvsutuqfqqqxt8mjngcwfr34k22nw5fuhw7may4akketqplcu0vdd7xeetz2cyqe3mf4g4aktk36tzxmx2fu27s4ttrh4yd4g5szsj2wz5wtk8d3g47y9p6kaxzmwkgum74jwtqn929j4w4lhhxmx6pudcv340fskyxart475dpcl2ypw20qu59yz50c85da35qwstz7fnkqqm6g62qmc48v4wkj2jflpaqvt5g5ymuasxuyanjeqygryz6kvajajdgftdrxcv7aly2d08urxfaeg5rnz5gjcqgjmwkzzvw5x3uj5c5p64w98k86sz4m6us30py4tn0cxh6q9gcwxz4vuuzy32lmxr029qpmn2f0a4fzfq94edt96765s8fy0quq55zy0gu5yme9hxz5ze2rlga4fgkx0kpng2rgjj0yktfxf5pw5qq9vjf24twgm2vyg5zhk2gqu808q8ep5ne99xs9rjezutn6czxahqusscwypfs5n56ydcngq29dlg0p675qcmkpt062vccauw6dudhr0522q9lahhyz5jmlt5guq8sm7g6c5u2pmtu6502umzxfk0fd06g95zrqhgjf8e2gvwcx8q5ty4ds4phhkff6ek9xs7xxp4aqtlc9rghmjjv3tpvgxv2cq5eyj7smgjfkt2kh3gsuemd0r7ptkpypvrg8ekk9vyu2uxczsj9rw2h689s3vnpuhymqs7kztpxqchdyut5fmk9sjwrzghwhwauwr9ckf8qkp4mh2f9kfgw7jhfmawwynx7gsduts38chvgca4cg0uusnequvrsn92zw7ky0m8ycmmgu88g8velvkp8xl3w2n8ds6vkqutnyffqxf09snuehvff4wzxn4h2q5empzg6akyvm4y62geavzppkv9q2m2xmj42dea39ydpngxhch4e4vn0eu7kx0dwevzc5kx9djj6yfvs8cspgj07qp9wyqytw6852cg0e3qs43rqyraacj4gvvxavdwrhlg223xjck2muhz4q94uwh2qzdyku2xfy6gncj47xf4ypswpunv4gdj5ar63rvv5ksy3ngwkukz4kyve8pp6v52wk6tchx4jwjy0yzkwv83gz9xcuuq437e7vd4m2sgz3phpk9yjq57e7j56ksznjgrmadzz82xef48r2k548d52zgqkk8psu5pcjj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T05:42:02Z"
  mac: ENC[AES256_GCM,data:nD9SNbmOAaBpLgLt0X7NYMP3GY05vCSDpkmocleTQo1kc1VcpTAuwRISY2qrrgcPm7EkEylzRAQgOWNRQzIm/CroEV8voz7R0zi/9zpUmMIjleMS6lkK7sGDIoGRVw6Dct4VE2GJajLFE31Zov7GGnCx/Uwx6zt3Se1weOTQv4w=,iv:u7Hz7E8ShRfGiz9QXjx+qnpyxuEVxJlyhyEzRru+LbY=,tag:7LSQjQOKAVTZTOeK3vAW0w==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
