apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:i1vvTjcUuaWxyv9Cra24pXscCkER9ApnT/qC1/QRNws=,iv:tou5QPj58f57PImi3qVV9dGVv1fYyg824rcZiQ4m8m4=,tag:/R0rs0xh+0YmWTNOWfBivA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGc3UDc3OEli
        MzJaak9lUTFvWmFtN1FTRmZZNElEVlNNdXYvcmlyQWZkTlVqNmUzaldwRzJEbldB
        enA3dWRTQVg2T3o5c2F1K1RNV0Q3bWV6dXRKSjU0bXFDell0NEJLYklmemdzMHgw
        YVYrVXI2TkRCbjhYZ3pEd2NQUUdJUzlDcHg3VXhBNmkvSGVvT3llQnZrT1loOTFX
        NXFqdlJSb2NZdHV3blR6Q2V6Y3EzVUk5NGZiRmFOc2VlL0F1dU5EOXAvblRjUTRE
        S3lOQk12cHMyZ2cvRzRON21mdXJPMjVLRWtHbldwelU5dHFjRXd0UHU3UEcrVW9k
        U3k4NFBBU25XdE51WlhSUGRRZFp0SzJpWHhJYTBaOHJFM3FUWEJ5S3NteGRhdjZt
        S2VTWjNKU0hPVDJ0Nlg5bGwrQk1mUi9oRCt1UG80WWdaSElRbENmaGRDU2YxTmll
        bkJmd0IrcFQvYlNTQVpxUFNNbU8zTDBqT2ZJd01DYUd5aStYbXorL2RUbkY0dnQ4
        cmJVcTUzSksrNE0waVVvSTRZay9ZQlFwRDhFS2ptQzBsTHhiZzQwME5SRThxUmwv
        eVZHK0ZTb1Fpc2NDNDJqSlFuZmNtNk9HKzlyV3Zoc3BwLzM5Z0h6Um02a3pPcjVX
        V0RzS3dpcXJ1KzRCRDRNQ2ZCaU5yRXZ1YjM2VW5FejAwd3IxS2I5ajQzeXh2YnRL
        ZzJjZ3g2QVBmR2NyWFFNMHBmdlFiT1p4VytCTHpOdXZmVVVJWGtKTzFFZExJYVlW
        ano0MWFVMzA1RWhkNVV0YWRTZGw2ZHN1MktJL1FzbHpNSHNMSkFPWHJoMUhnVHln
        bGRvRFZQU1Y4UkJqc2hjeGdjZmpqWDZCTHE2YzRoZEJZbGRrV01LaGV0K21wT2V6
        UlBpU1NUSnFSN0tYYmhJOFZzeGhockM5Mi9id25WSGRBT1pidDZYM1FZbXpkRnJZ
        QTJzSmpsRHBBV2hGUzBEUEp4WSszd1BQNUZrTlB5UnphLzJpWnNGK0FPYXdXUGNm
        MXBZU1pmeTRsZmxqZUlacGNWUDlkRU1wRmhCMlptTzRaTi9ld1lSeEVWNDdtbFIw
        RVVMTk1Na3hrd1lxMWV5ckRsS3dLL0IvcnZuMlpvY29UaUVLQXRIc1NLeDNXUENm
        U25OcitHUXM0UHNBOGhtamN5MGZ6aWNiYkJLd2YvN0szZ1VySXYxWlFwZzZ4U1hX
        ZW1UWHZ0Y3MxWmNhbEgrTHgrdThQMFhTSVg4ak5HN05PK1ZJYjFYYTdtdmNHcHE3
        Y2VzV2YxSmJwS2RlblovMjZvNnU2QUlNUko2MDl1UmNMZGk1V0Z4SDA3ajlycFBO
        aVNicGk1Nml2UWRaOFBYLzlXNmhGR3JZSGVhTnFqaURnZ0xzMjlGZFQrNDhCYzc5
        YW44aG5kQU9zVjhQL0J6VEtRTFhaU2tQdU5MVnBnMkt3bjNJMHZTQzJqS04vOXNh
        aHdORXg1VXRMdnJqU3VrR05hTksvcHVxMEZ1aDltZkV2djNYRnhoRVB4NnR3elds
        eml3SFRGY1MrSkE0bHp0RmpKYXBoTU13N055bVlFaS9Rc1dDUUxjWlhiWU1xbmF4
        MlM0Sm9yckFodzhLUVp6dlFDQjFWQ1kvcDd3cnBkeGRianFEV3hlNFAzOWtRdjdO
        d2VLM2tRbHNYQWhFQUtBcExNckV2N2piRW5XQmtwSEphVnFQWmVpVHdnUWtQYWRa
        TGlxY0lXdVJreDN4a1BSWkZGSEdybmJJTDcxN2x3WUwxZjBOSjlZd1FGZVNrbml6
        bkd2dzdvOWxTZXkvZlBJWVRRUzRxUERIb2xUblBaTEcvWTR6NGprYXJGTGlOcUI0
        NnhqbTh5VWtOVzY0aU5DelRTQ3dpbm81NUEvTHlBUDN1WXBPV2R5czIxaGRsdmZR
        MVcvNTdYa25kKzY2ZTV0RWNMZ2JSMkYwQk5iZlRWSzJBV0tsWGZPMjIrZnNNUQpC
        aVlCbzZSanUvSzh4bWpXSzFUREtkUVZMaUN6UmZNa01WZjNWcHc5enhjCi0tLSBu
        dXFoK3lUVExqN2xrSE4vbWhkcjhLLzNvVXY0WnYrQU5FczJrS2NLUFU0CsPU6uUm
        RzzEraGCOhka3zHd591wb7pF4vuBiDcgKb9rQAOBQ6kDCV/IBQiRkBsN07F6tuv1
        PBnxosuzVEGuH+M=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z2790e0enqwlpxt5q5mrgd59tx92fqfpeltynww0v46tmyd0jxup9x53j087q7vtc3zuhzdxp94hxthxnfd7rtdl2uz2d6jwwdueknvcfesczsmexd2cmgfet2ypxplsgxlzy6rgf3rzlx3907qrfl3sk4lexu4rs496hyms0vn5x624xycyqh08uj73kwq2vqxz5a6cpy02ssrtzfxwuzey5kuy4pzekrk2r92pvwmes2rgf8fnls4njw5hrx4a8x99tg58vm5j4zfux4a2vr9q0yaj72g2t4rhc0vv3g4z52842a782ppu50gyqwet0xsr9g2s8ny0zqjvmz5p9vp2wtnuexnkvg5tl4e9v3ep45gr6q0ryh03uvsvnz7dr4ftjmk42k2gwc22esyjvg4dg9uv6sx4cyjthwk7zx5y8aehnk9pvmn3yyygvx2d99vynvvra0gtal02y3axnfpxvxhsjg94sy58kld5yuggzw9s9j07gpj0au5utsv4c34yj6yp5pl3j4sc0g4z50ngp7xajxdjt9jytda3yc2un6qrrd3hvsypxag987e76tktgqqjfd23gwu0xzc6extlqv9faqa2vzn72m8xs9hvn6qhm9sxhpkmv65wwa4quu4jwnp6sf7vakavw4z2kgxp2j55glprp29j8v0uhyftsx30n3ejxd2g409zyt9xh4jnw2jc20qms4z6l4v3eflqnxqs8n5x3vc6dcv590kpnx36tythvsutuqfqqqxt8mjngcwfr34k22nw5fuhw7may4akketqplcu0vdd7xeetz2cyqe3mf4g4aktk36tzxmx2fu27s4ttrh4yd4g5szsj2wz5wtk8d3g47y9p6kaxzmwkgum74jwtqn929j4w4lhhxmx6pudcv340fskyxart475dpcl2ypw20qu59yz50c85da35qwstz7fnkqqm6g62qmc48v4wkj2jflpaqvt5g5ymuasxuyanjeqygryz6kvajajdgftdrxcv7aly2d08urxfaeg5rnz5gjcqgjmwkzzvw5x3uj5c5p64w98k86sz4m6us30py4tn0cxh6q9gcwxz4vuuzy32lmxr029qpmn2f0a4fzfq94edt96765s8fy0quq55zy0gu5yme9hxz5ze2rlga4fgkx0kpng2rgjj0yktfxf5pw5qq9vjf24twgm2vyg5zhk2gqu808q8ep5ne99xs9rjezutn6czxahqusscwypfs5n56ydcngq29dlg0p675qcmkpt062vccauw6dudhr0522q9lahhyz5jmlt5guq8sm7g6c5u2pmtu6502umzxfk0fd06g95zrqhgjf8e2gvwcx8q5ty4ds4phhkff6ek9xs7xxp4aqtlc9rghmjjv3tpvgxv2cq5eyj7smgjfkt2kh3gsuemd0r7ptkpypvrg8ekk9vyu2uxczsj9rw2h689s3vnpuhymqs7kztpxqchdyut5fmk9sjwrzghwhwauwr9ckf8qkp4mh2f9kfgw7jhfmawwynx7gsduts38chvgca4cg0uusnequvrsn92zw7ky0m8ycmmgu88g8velvkp8xl3w2n8ds6vkqutnyffqxf09snuehvff4wzxn4h2q5empzg6akyvm4y62geavzppkv9q2m2xmj42dea39ydpngxhch4e4vn0eu7kx0dwevzc5kx9djj6yfvs8cspgj07qp9wyqytw6852cg0e3qs43rqyraacj4gvvxavdwrhlg223xjck2muhz4q94uwh2qzdyku2xfy6gncj47xf4ypswpunv4gdj5ar63rvv5ksy3ngwkukz4kyve8pp6v52wk6tchx4jwjy0yzkwv83gz9xcuuq437e7vd4m2sgz3phpk9yjq57e7j56ksznjgrmadzz82xef48r2k548d52zgqkk8psu5pcjj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T06:10:00Z"
  mac: ENC[AES256_GCM,data:Z0Ym0GBy28YxyrrYINJD6pTFGoEC0GtdNR0VH/dj7UpFgFHWY9UIWZnzY9Ow9FExmwBPM66e4lZGwakS1dRAqW6h4cd2VwocCZ543p4krAoaPfAu6iPIw+Co+nCjm/IL8rEt2DsMQ2PrZOeLnAOlNC9Cgc/5AdAX33yrpIbz808=,iv:nfoxVDT6lAoB8DCTmK9aL3Aputoa3oVVMyNL6PgstaY=,tag:TvmlXOokPRn9c3/C7m7P7A==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
