apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:bZZxLq3uWswJZgdyO6ekCpebbUV1+DCQEt2GjsodwznUPGqfQffSw1j7pqS3dfPjYox0cEU0rBVvEXWlEYf6Cq/KoEJasm7+DCorFu/AyVmf4IsalI9ml609qs5PFdi2AHLKcar44p18IF8xvw/lWJcXyhHLECvRfE9WA58nVH6TaKzeNt9FOZTLLJ8X6HfBvBMZO7omUothcvqZ0K5I8ujZS/9Rh1hAq3EykI3FdTsjHf9z,iv:gmihS09b2bk8Y5AGwtGnhuy+GvtayMfKn9+aogSQ5DE=,tag:II9nFkXfqETnMT9pPVeBlQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFUvcUpvRGh4
        SW0vcFhYQWltaG9MTTdYVmthbmVhVTN0K0V6bmgybVRYS1BjNzFmUkh5TTNKV2Nj
        anB3Ujladk1RQ3ZBclE5eDRTSlJkQ0tNK0tSZFR6eTA2VXZwSHZJVjdmTzlrQ2ZY
        eWlLRVEvbmcwWXNIQklaNWhvYi9hNWRJdnF6RGF5QlpCOUpZcndNZUE1ZTFTOStx
        ZzZETjdGOVdkSkp2VEFHY0FkWVN2Ykw3eTk1L2psQithTHYzdXhpWmowUzE4NU9n
        Snk5dGhCb09URlhUbUd6c0xSVG1QamI3M0ZxZDlHTzd5UmJZOXBuQ1pmMnVYVVNm
        QXpueG9MWnQra2tiR3pMamExUGRZelUyd0hsc0VJaXhSVjRGMTVzbkRtY0pmZytk
        WTRVWjNoNnhhRWNCd1cwWFZxT1F6bUd5RkhwdkVDSis4VGZkdHdBR1MwVFdCd1cr
        TEN1dWV1U3JnOVpZV0w3MnBmQnc3WmlVQ2dXNmpONUJBR05uM0VleDZpQS8vNVhu
        Z2lNR0s3dVQ1SlUvS21Obm92SWxsRFU5bUFidDgyTjJvbVMrZnVqYmYrNVhkQmJN
        RVJjdXpNVkJYRXRXZFlEZ1g5YkNwaEM0d20zeDNWUUh1WU01Q3UxVk5vNnZhWmhy
        YVlMV2FHalREMnZyY2lWS2tNYWN6b0YxbEhNdTBmS3ZCZUg5YUVyVXI4MFkyenJv
        cktXL2s4eU0zdGFEdTNwSVF6VDBycnpuUWZTSUdMZHdqZ1UybkI3dExMejd0Vnc5
        U2VDWW9qTXd1MFdOcWJLbmtEVzdTUTAzalUyYkdKSVF6N1htTVdza09HUTJvVG9F
        N3M3bEZnVnExaXVLSHdvcEQwZmR2ZXgxOVIwaVd3RWJ4VSsrVEJYUlFwRDlReDVp
        TlYwSkpzQXhoZzgvTGVGMGlsaFZId0dWMWVzQjFWTzd4MFk3QnBTY1VkVjhDWHVF
        Zk5UZ08zUjBCOWYyUUViVEkzV3RHejJBSlJOS2dYWmRqQU0ydVZUajhOaTR1Mll5
        YVJZYjZMckUzMmgxUWlDVzV3bkY3eHRIb25mVEJPeXQxdDhIQnF2QUVuYUtzREJW
        LzhTMDJBQUFsTVV6dWY3aXdMRDhyeFptTmQ4NW5iVzdsVjE2cloyaDBtNFpNbWdj
        N3FBNFpyQ1JxZ1JFcVFDb1BWeFQvbHNzNFVFb1NlZG1lQzVEbzZpZklzYlUrZlNW
        RVBhVkEyWGREMXlud21ENGZJekludWNLdEo2RjR1bExyaDRiZXJUS1BSY3FIc01n
        cW9HbjJYRTltTDBiNTFUUUQ5NGpLdnVDb040UlphNElHWDBqS3FDcEtxOVJnalVB
        RGZRM21vZUxOVWhVbFYyUkJYUVNLME53NTlCWmsvbDBxSUtOZHhDQlQyeXgwWEFj
        ZHdRV0JxcjhzcFRCL05QUG5yMWUzU25WZDNUUU5weVFRUW9tQWZIT2hIUVRrMG8x
        YUsvdkx3NFIxVWJLYXdFbWVZYzFrcnY3YWtJZWtURTNoZ0RNUU12WE9qSjBNQjhk
        bE85VHloaFp1bGNXVytLQ0E1SllPUVlrS08rQytPRWh5V3dJMjRROHRkVmZLTUxS
        Z1hnUm5wNjVmc0ttanRYTWVpTDNmRVZDZ2p5UmlwMGJrdXQ2Y2ZqREhyZVNOaURp
        TkhIcExxZUVDQklxM2ZZNDJkRmZ6RkhWUGRONmYzVFUzUzdFczRpMjVqSEs0V293
        M29uYm1CRklOMGhhRlVJTjYyemxxTkpaWlJFU0V0NFVyQVR0TlkwYWp0MHMzalp6
        SVFBc2p0SGNLdDVYT3JrSkQ0S2NpQytkT1JURUtTdFlScU96YllLbjg4M2xJK1Z6
        MWY3K0RrYWNIOU82NDFvb1dyOFNiS1A0TVlyYXFYV3ZqTERBaCthaUlIdE5qRGta
        eDJsWFpxUmYyTkNOM1ZhQ1hRTjIvMk1IS1lKdTRWYzcwVlR1MW9ZZm15N0pBUQp3
        MWJPbG9xcm9EREVxM0NvUlhmZncyVXVXRVJMNFk3S1pGMisyUXVGZytrCi0tLSBI
        dlNWbEIwalYxSEFaa3VEQ1VOYnFjVVlvS28xbFZHNkIyYzBid0E4QXVzChVtjApZ
        FOX6RyE/g5aWO5x5QZfF/7h8Tc1aWumSOEKEqULVc/4cV2nyhdvX712nbC2yUJXw
        R5A+gBJyXxbqi1Q=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z2790e0enqwlpxt5q5mrgd59tx92fqfpeltynww0v46tmyd0jxup9x53j087q7vtc3zuhzdxp94hxthxnfd7rtdl2uz2d6jwwdueknvcfesczsmexd2cmgfet2ypxplsgxlzy6rgf3rzlx3907qrfl3sk4lexu4rs496hyms0vn5x624xycyqh08uj73kwq2vqxz5a6cpy02ssrtzfxwuzey5kuy4pzekrk2r92pvwmes2rgf8fnls4njw5hrx4a8x99tg58vm5j4zfux4a2vr9q0yaj72g2t4rhc0vv3g4z52842a782ppu50gyqwet0xsr9g2s8ny0zqjvmz5p9vp2wtnuexnkvg5tl4e9v3ep45gr6q0ryh03uvsvnz7dr4ftjmk42k2gwc22esyjvg4dg9uv6sx4cyjthwk7zx5y8aehnk9pvmn3yyygvx2d99vynvvra0gtal02y3axnfpxvxhsjg94sy58kld5yuggzw9s9j07gpj0au5utsv4c34yj6yp5pl3j4sc0g4z50ngp7xajxdjt9jytda3yc2un6qrrd3hvsypxag987e76tktgqqjfd23gwu0xzc6extlqv9faqa2vzn72m8xs9hvn6qhm9sxhpkmv65wwa4quu4jwnp6sf7vakavw4z2kgxp2j55glprp29j8v0uhyftsx30n3ejxd2g409zyt9xh4jnw2jc20qms4z6l4v3eflqnxqs8n5x3vc6dcv590kpnx36tythvsutuqfqqqxt8mjngcwfr34k22nw5fuhw7may4akketqplcu0vdd7xeetz2cyqe3mf4g4aktk36tzxmx2fu27s4ttrh4yd4g5szsj2wz5wtk8d3g47y9p6kaxzmwkgum74jwtqn929j4w4lhhxmx6pudcv340fskyxart475dpcl2ypw20qu59yz50c85da35qwstz7fnkqqm6g62qmc48v4wkj2jflpaqvt5g5ymuasxuyanjeqygryz6kvajajdgftdrxcv7aly2d08urxfaeg5rnz5gjcqgjmwkzzvw5x3uj5c5p64w98k86sz4m6us30py4tn0cxh6q9gcwxz4vuuzy32lmxr029qpmn2f0a4fzfq94edt96765s8fy0quq55zy0gu5yme9hxz5ze2rlga4fgkx0kpng2rgjj0yktfxf5pw5qq9vjf24twgm2vyg5zhk2gqu808q8ep5ne99xs9rjezutn6czxahqusscwypfs5n56ydcngq29dlg0p675qcmkpt062vccauw6dudhr0522q9lahhyz5jmlt5guq8sm7g6c5u2pmtu6502umzxfk0fd06g95zrqhgjf8e2gvwcx8q5ty4ds4phhkff6ek9xs7xxp4aqtlc9rghmjjv3tpvgxv2cq5eyj7smgjfkt2kh3gsuemd0r7ptkpypvrg8ekk9vyu2uxczsj9rw2h689s3vnpuhymqs7kztpxqchdyut5fmk9sjwrzghwhwauwr9ckf8qkp4mh2f9kfgw7jhfmawwynx7gsduts38chvgca4cg0uusnequvrsn92zw7ky0m8ycmmgu88g8velvkp8xl3w2n8ds6vkqutnyffqxf09snuehvff4wzxn4h2q5empzg6akyvm4y62geavzppkv9q2m2xmj42dea39ydpngxhch4e4vn0eu7kx0dwevzc5kx9djj6yfvs8cspgj07qp9wyqytw6852cg0e3qs43rqyraacj4gvvxavdwrhlg223xjck2muhz4q94uwh2qzdyku2xfy6gncj47xf4ypswpunv4gdj5ar63rvv5ksy3ngwkukz4kyve8pp6v52wk6tchx4jwjy0yzkwv83gz9xcuuq437e7vd4m2sgz3phpk9yjq57e7j56ksznjgrmadzz82xef48r2k548d52zgqkk8psu5pcjj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T05:54:05Z"
  mac: ENC[AES256_GCM,data:oCKmkmh/QZx8a5tGf5m0HVcK7MQc4w9S4vDQntlfcQUeTUIygpjHeGrDnyWvvRoPXFaJ2/YiLbTGqKmq6breAo5+GrK42DEWh9QlzQJuSpp7fEeFMQZYsNEUHoItkArPGH/0EKDMO9J2BcqTiGR9fORGQ/3szGXrDADciWeTH10=,iv:TYhlWzgjqqSFi7/D2iKbVPLq7rc2Y0CSqqGVQnvr7D0=,tag:FGWqLB8Gs3Jy385c3k7sog==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
