apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:JS7idAIQdDuVb1nPTop57cAW81SFez+OWc3E5BG5O0hgl8NmLOJ3gDxZ/KC4w/FPPSmza0HkFUoYd5jBzkXhqpcmgIIsPbXc6oDwqiTiDgI3mRpgOY7bHGMGgsfocg9ETswHKatQAa7SEolCdQ+LiLmBEFVkqz72VyT3MVSZ8EueOmLcZpjoa07nVAKRGi5SzzZysy/yj3JzvgfEbPfddxzsVj9g1/lAiBNgt9ts3BM+rB29,iv:vJGB183nBe7eQpJwQq4bydLLt7eRtW5iepnQPxdMaHk=,tag:F7LnVYG26LxtaGbSZwuvbg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEs2WHVhc0U3
        TVdGcEV5aER1Rm52eW15TnRFaVl6Ym1vSkVsMTFHajJsamppcldnL0pWeHp5dlYr
        Q3FzYi90YlVMT3ZISUhFZmZyL2lDUjJQd3RNODVnOWVGMXkySXdadXpLa005M0sr
        U2t0Z1ZrNDhwTEdyZHRNN0NSbWlrbkNidlBsZm5YYTJtaUlGazdndXVmWFE5cjMx
        RWNveEtMY0RlQTVtc3pYRWN3dHlFazlHYU11WWFXOTJRWjNCTFFocGNtMEdHSDNU
        ekpHQk03cW1SVndQSWRvMVdwVHdKUTlqLzB4OGEwUlNPZXRRZmVFZUlrQ2NQbmpJ
        K0w4aFBhYW9aSWN3OTd2TFJrVzBxQWQ2ZitZc2Y3RmpBeUM1dURUL3F3eWZBNzIx
        OWFLbUpuVDhjOFVta0xVTGdkYm5BaTZQUnI3cUdId1NVWlRXT3ZnTjNWalFoa01I
        ZVZnWGRZc05xTS8vSGFUbDZMZ1VVaTQrTktpaDIzOW9aMUpIYmdWRzZ4a09QU2t4
        eVRydGtIZUtYSjY0WmJnd0Z3ZC85SC9FNjMzT3UvdTFoQ2ZNNFBJMkpkTGNQSmI1
        YzVqdVdLRDVSb2l5SGM3ZDNhZXJETEc3cERpTDZhMTlac2xPYTI5RmxEV2tQcklP
        WE9JR1RZeGhZc1VQQmg1QUJiVk1YaStvcHFmQ3pzbHR3YVRTaDY1VjBiK3NsdTdU
        b21wZVZTUDZGb2NVSEhFMmxxd0V3eXlsNkQ0Zk5HdkVwVWEyODlMcUtXMTdYRGZG
        RUg1WVZoVzJjMkxmY2N1M0llYWhBK3l2TkNwTHV1eE50TzJ3LzNJU0dvSVk5aUo2
        dmxxNUx0TEk0RzNibVJkeHRaYTZUT05SY1ZVZE54UXh6dDNzamxPU1ZmcWhCdWxp
        SHIxNUVtc2NKa0FFd3BhazRYeHlqNFV1UG9SS3BwUlh3eG5QeGcwRGdLTUUzeHQ4
        WTF6ZTRxRmEzbDNwRFc4TDBpbmdmYzJPT2xLWWl5RGYvZ0t2bnJ6a01EZUdJRkE2
        TUhaaWlhM204Y2g3L1JMVEZqUExFRFpBODFqbnNaalZrSmxNc2JaaE54SFJnR0tH
        V2dvM1Y4NUNrNmRsTU04aWVkWDIwdGlSTExlTUM2eFR4RnVpUmNDUVJCa1FmT0xD
        TG01Ris1Y1dzVCs2b1UrL25QaUhEVGJORWxEeUMxLytiSjNwa0JKdDB1NlprYXFM
        UWU3UmsvenFuanByZ0VrcTJ6TitkUWtQWk4wbEFpZUdzRG5jcW1xcjl4SzdBSTVB
        NmQxR1BJZUdPZHBzZXFJVkQzMDd4OXhLdFN0WGdyeUpiUGdPWmUvZjdQVXhvNEhF
        WjRNSExXUndpM25wTlBPeUJRT3lDdTE3U0U2RW1LbjNFN0YvQzlKSllRVVMrOWpz
        RVhXcUFldWNEVXYrTTdSckxiQ0J5VHFXS0ZMQjN3NnVWZHI2WGJsVisyc2hxVndJ
        aktOeEtVbnB5UkxZVURJNnl4ZHlXNHphR3dUUGRyRnVSTkhIaWtORlc5RWphVjA0
        alhjL0lIaGJuVnhCRGpOWHZCMDZWVW11UXAzMW1mUTE2Z3FYeGxocytJbXRBdEVo
        OVc2ZDN3cHM5T2wvU0w5YzVUalNJRGlnN0NINnIyUjNYYXViclVLSDJzT1dqZCtp
        WGZmZEN1NWZCcWJjR1NDYko0bHNwbjBGWTdKTEduTHlPSWZ0S04zeHQxNktIUW1h
        Y25hRmt1YUw5N2Y1SDFNeWdSeFFubWtIeEVJZGJjVEprYXFXOTl0TUZTcS80dWZS
        OUtvUk5CY2d3dDZtUGliZ25yYWFvYllEdmNnRi9hREJKWVU4K2xuTjcxVGpYQ2VQ
        T09hSjFKTTdPSjZPbGJNTTBuUWZiYzgrWW1NR09HZkpEbGpWSDdNK25oUkFCK1h5
        dHhyVm5iVnh2a1VsMGRwUmtabGU0M1JaVjFaZW8wVHRZYzcxb0tBTS9JSDVOQQpT
        WklLNkloclBDNVN6YkRvcE5LWDR3WjFHYUR0YzJxYlgrWEdmY1JieGxnCi0tLSA0
        cEdlZEdiUkJMRW95QzZLaERlcHIwWXNEaS9GbDBMNVRBYUU2alVuOWF3CviiW7Pl
        uy8IRnoaCwvQ0JZQuZ5NwL6Snb624BSwoaEkYP4DJbCqDnwN+nXoiTaRazO4GbfG
        x/J5o9We7+esh0Y=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z2790e0enqwlpxt5q5mrgd59tx92fqfpeltynww0v46tmyd0jxup9x53j087q7vtc3zuhzdxp94hxthxnfd7rtdl2uz2d6jwwdueknvcfesczsmexd2cmgfet2ypxplsgxlzy6rgf3rzlx3907qrfl3sk4lexu4rs496hyms0vn5x624xycyqh08uj73kwq2vqxz5a6cpy02ssrtzfxwuzey5kuy4pzekrk2r92pvwmes2rgf8fnls4njw5hrx4a8x99tg58vm5j4zfux4a2vr9q0yaj72g2t4rhc0vv3g4z52842a782ppu50gyqwet0xsr9g2s8ny0zqjvmz5p9vp2wtnuexnkvg5tl4e9v3ep45gr6q0ryh03uvsvnz7dr4ftjmk42k2gwc22esyjvg4dg9uv6sx4cyjthwk7zx5y8aehnk9pvmn3yyygvx2d99vynvvra0gtal02y3axnfpxvxhsjg94sy58kld5yuggzw9s9j07gpj0au5utsv4c34yj6yp5pl3j4sc0g4z50ngp7xajxdjt9jytda3yc2un6qrrd3hvsypxag987e76tktgqqjfd23gwu0xzc6extlqv9faqa2vzn72m8xs9hvn6qhm9sxhpkmv65wwa4quu4jwnp6sf7vakavw4z2kgxp2j55glprp29j8v0uhyftsx30n3ejxd2g409zyt9xh4jnw2jc20qms4z6l4v3eflqnxqs8n5x3vc6dcv590kpnx36tythvsutuqfqqqxt8mjngcwfr34k22nw5fuhw7may4akketqplcu0vdd7xeetz2cyqe3mf4g4aktk36tzxmx2fu27s4ttrh4yd4g5szsj2wz5wtk8d3g47y9p6kaxzmwkgum74jwtqn929j4w4lhhxmx6pudcv340fskyxart475dpcl2ypw20qu59yz50c85da35qwstz7fnkqqm6g62qmc48v4wkj2jflpaqvt5g5ymuasxuyanjeqygryz6kvajajdgftdrxcv7aly2d08urxfaeg5rnz5gjcqgjmwkzzvw5x3uj5c5p64w98k86sz4m6us30py4tn0cxh6q9gcwxz4vuuzy32lmxr029qpmn2f0a4fzfq94edt96765s8fy0quq55zy0gu5yme9hxz5ze2rlga4fgkx0kpng2rgjj0yktfxf5pw5qq9vjf24twgm2vyg5zhk2gqu808q8ep5ne99xs9rjezutn6czxahqusscwypfs5n56ydcngq29dlg0p675qcmkpt062vccauw6dudhr0522q9lahhyz5jmlt5guq8sm7g6c5u2pmtu6502umzxfk0fd06g95zrqhgjf8e2gvwcx8q5ty4ds4phhkff6ek9xs7xxp4aqtlc9rghmjjv3tpvgxv2cq5eyj7smgjfkt2kh3gsuemd0r7ptkpypvrg8ekk9vyu2uxczsj9rw2h689s3vnpuhymqs7kztpxqchdyut5fmk9sjwrzghwhwauwr9ckf8qkp4mh2f9kfgw7jhfmawwynx7gsduts38chvgca4cg0uusnequvrsn92zw7ky0m8ycmmgu88g8velvkp8xl3w2n8ds6vkqutnyffqxf09snuehvff4wzxn4h2q5empzg6akyvm4y62geavzppkv9q2m2xmj42dea39ydpngxhch4e4vn0eu7kx0dwevzc5kx9djj6yfvs8cspgj07qp9wyqytw6852cg0e3qs43rqyraacj4gvvxavdwrhlg223xjck2muhz4q94uwh2qzdyku2xfy6gncj47xf4ypswpunv4gdj5ar63rvv5ksy3ngwkukz4kyve8pp6v52wk6tchx4jwjy0yzkwv83gz9xcuuq437e7vd4m2sgz3phpk9yjq57e7j56ksznjgrmadzz82xef48r2k548d52zgqkk8psu5pcjj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T05:42:02Z"
  mac: ENC[AES256_GCM,data:2RnAHMoBXkdR084A2+evlAEHX2ZUtNW69lyy7ZXcqx4W0maTGwXwEe48eIqq8OKLdjbgMbUSkuo5qpUGF/VbN9FtALb/KJnSRXsNNKKAiDVGmunc8Vw16+e+8PWhEVAyT6zXb2PXPM8vxc07bsLKcVW3FxQ7XlBexAXO5x1t7VM=,iv:84wEOiZcG1TxKqu0hZcGTUPlveClbqxui2OnGBcaQnU=,tag:ZyTHVAAH9X0x0r4Ddlgq8w==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
