apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:3ZTIuWtMG98GQhYQpX4ZiZMj58VqMqIfeVHDGO0UXUB+3plVQm/aKMArGmuAw73S62Pf01gDRObit3A7VboxZdjZ0kH+XMjqh8sXtGPIa3FmVfvWpppEyE8BkP2EF65IZ7NDpXwADFtcOZN2l+cRpwKnty5XB2OzjrIFvG9XzVvdtZiEXTjATxrZ4RRFkM6Px7C1yk6Ef7ZoobywG+Acrkz4XcV95CNIMCv35loArwTKLPlG,iv:A6t176t7WOdgHOYT2kHvswWY3v3WuzNUCKS6WGsShaM=,tag:epoUxo7Jb++gZdV1EytDQw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEphQkVUNGNP
        ME92eCtpd2VENldJQ1BZWjBxSVd5WXRlMkMvVkpFS1NDeFA1SkpwT2dpYk9hVWg1
        VVhRRGY4V1Y4L2FTclIwaUtqaFRpUlVubFptNUZRUDNPN2MvNXJtY3BydEt5Nkoy
        TE1ETStXV3NKUnJSWGhHYko3ZFdhMkRHTFFjYUl6cE9rV1pONGtKbXZkR2d6NGhF
        L25WQXVQVGVEeHRrOWdDdnkvRnp4ajIxNEZjSndyRXR2eDU2Z3ZvTGtMbk1ldzc2
        RXk1ZVJRWGhFSmVqWHhRM1J4MUhVWGUxVUN5TFdDTm9lMXcraDVpUnZrZG9JV0xa
        YkFRWXFvY3Y3bEdLSkpnZUdEcWhjK2o3aG90K0RyWHFRWnBhZEpuRGU4UWFjVVJL
        cVFqZjhqeHBVUzFybnlsQTlpOHNhMXM3aGNoQW9vUDBnU2E2WjhTZE92U3RsS3FQ
        OWJ4OWJiMEJqMFpBdmxtbWh3VlVET2QzOFVHNjVjQUZQUmJCaWJ0UndvZ1k0NGFP
        RVhmUHMzeTBjM042aVNucDhiL3lRdXdQNkpEaFRTR2dSbFVsN203SG1aM01mT3Iy
        KzRZaGExOWhaTEtheUxMbk15NXEydkF3b3liM1Z0UW15NEV6bG0vN21pdWV2QnE1
        c0E3YW14L1RWWXNDOGo5bUhDT2tRMzJhNEN2L1NDRlQ3TEVGd1VPQ0tCSjYyek92
        QUc1c3BieEZueEdNSmJOVVhSVDZLVEY0Si9NM1FBemZlSHNNSW5jbkovK1JJSGJr
        eVB3b08rSCtwalNwUVRUaU1TS1VSVjc0QStUNXFOT0tMNmdMSUh2djNybEpqT0xK
        aXpJMVZHaUtxTSt0VzZLSGRzM2JxTTBjamVvR0FmeER6ODc5Vm1nYWVUR1o4VWw0
        aUVWZGlpUXdIcDNPQmJjNEFMN0ZKcU9JWEhReC82WTlpQUxaZkdBWkdtTFJYWjRS
        SjRGdHhDNHVoM2dXcGVQdVFjbEVQazFlN1NCa0JUS2hxRmkveVpwUTBMNDJLMnZB
        VVRpc3ZqTkowOVRCaUYrUUZiR2JuZmZHVHVJb1VEMlE5OTc2Mit2SkdzTGhoUUN6
        S2QrNXN5YmNDaFlOU01hWERmNURSRGppaUNMQmk2OXM3MVVndUE5cllRLzdKNXNZ
        QmVCSlBCRlViQUhSZzFacUsySUI5Vm41VDJqQlVPRnBNakxQM2ZCd1FFcFJWM3VJ
        Nk9id1RvQXVaeDE1QnFvSDFRMXcrQTZlZ05DVDV5T1RldVVxSkFPRk5RR0tZT3U3
        aFFoVko0M1NJSHdLNkdXM0VlTHNZZEY1ZUp1eWxoTGRSQWFuNVN1Q0gwVVhKREN6
        cjRvKy9ORWRPM1djYkNHMjhYWFBoZmFlUm9qdmZtRGhkek44bXZIUWFPWkp2VEhT
        N2pJTy9PNHg0dVhEajUyWWdoVnZZcHNJK3hCTE03eWg5eXgveUpETTZKUVNVWi8z
        QXZQb2xibmxERHN1VHZHNDE1VUJMNy96SVBLRit5OVNydTZESGxNMWMwRVV1S0wv
        UENxTnFCc3Q3MEZUWHB3RlYweXNtV0c1L01weEpBOFp3NERHNC9MTzNlams0d3VT
        ZFp2QUZCb1ZsTjhNNndRRFJpcjBmOTI5VUNMdktoVEpJVDE4eXRRTEFwNjNTRE1F
        VzRDUjZvY2J2MHFzV3U5Y282eVdsQ0t5aEthZWQ5ckQyb25RVnZKNU44TFROL0Zp
        dzVWMFEzWVFGNitPRExtdjZqM0JLSW9yYnNoVi9tY3F5RHdJeThWQTl6UFljc0pp
        WW54b1dVY3RwejA1ektOWXVKYTg4MWt4Q21SMW1HRkZUMnlNVUNkMjlmb3F0MmRR
        a3F0OHE3NTlMUEZGRHlCdlRpNkFFKzVKVlBiS0JhQTZyMG52bWY0WWdkcERFR2Jq
        NHZ2QSsyMEpQOFo4T1k4SS9MbEZSYUY5d3RoUnhCUEJGK0lmVTNsd0IzcnVUQQpK
        RGV0ZTRKVmNXcUhBYzFWTzBxZ0g3d0dRa1RzM3djTklZT1FTS1RIK0xvCi0tLSAx
        N2JwQzNTV21qd2dCdktReDVmYTJKN1JzVGdueFkwVjYrNWg1MkxibVdJCuNZSPRD
        lXAJCGkNXOMnFCAJ8bF3h2kOzGzcO8BkiRl3lyRbmGBjdo5R3IGZpEnGCff3HVo5
        JIDbchTE+H9qg8Y=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z2790e0enqwlpxt5q5mrgd59tx92fqfpeltynww0v46tmyd0jxup9x53j087q7vtc3zuhzdxp94hxthxnfd7rtdl2uz2d6jwwdueknvcfesczsmexd2cmgfet2ypxplsgxlzy6rgf3rzlx3907qrfl3sk4lexu4rs496hyms0vn5x624xycyqh08uj73kwq2vqxz5a6cpy02ssrtzfxwuzey5kuy4pzekrk2r92pvwmes2rgf8fnls4njw5hrx4a8x99tg58vm5j4zfux4a2vr9q0yaj72g2t4rhc0vv3g4z52842a782ppu50gyqwet0xsr9g2s8ny0zqjvmz5p9vp2wtnuexnkvg5tl4e9v3ep45gr6q0ryh03uvsvnz7dr4ftjmk42k2gwc22esyjvg4dg9uv6sx4cyjthwk7zx5y8aehnk9pvmn3yyygvx2d99vynvvra0gtal02y3axnfpxvxhsjg94sy58kld5yuggzw9s9j07gpj0au5utsv4c34yj6yp5pl3j4sc0g4z50ngp7xajxdjt9jytda3yc2un6qrrd3hvsypxag987e76tktgqqjfd23gwu0xzc6extlqv9faqa2vzn72m8xs9hvn6qhm9sxhpkmv65wwa4quu4jwnp6sf7vakavw4z2kgxp2j55glprp29j8v0uhyftsx30n3ejxd2g409zyt9xh4jnw2jc20qms4z6l4v3eflqnxqs8n5x3vc6dcv590kpnx36tythvsutuqfqqqxt8mjngcwfr34k22nw5fuhw7may4akketqplcu0vdd7xeetz2cyqe3mf4g4aktk36tzxmx2fu27s4ttrh4yd4g5szsj2wz5wtk8d3g47y9p6kaxzmwkgum74jwtqn929j4w4lhhxmx6pudcv340fskyxart475dpcl2ypw20qu59yz50c85da35qwstz7fnkqqm6g62qmc48v4wkj2jflpaqvt5g5ymuasxuyanjeqygryz6kvajajdgftdrxcv7aly2d08urxfaeg5rnz5gjcqgjmwkzzvw5x3uj5c5p64w98k86sz4m6us30py4tn0cxh6q9gcwxz4vuuzy32lmxr029qpmn2f0a4fzfq94edt96765s8fy0quq55zy0gu5yme9hxz5ze2rlga4fgkx0kpng2rgjj0yktfxf5pw5qq9vjf24twgm2vyg5zhk2gqu808q8ep5ne99xs9rjezutn6czxahqusscwypfs5n56ydcngq29dlg0p675qcmkpt062vccauw6dudhr0522q9lahhyz5jmlt5guq8sm7g6c5u2pmtu6502umzxfk0fd06g95zrqhgjf8e2gvwcx8q5ty4ds4phhkff6ek9xs7xxp4aqtlc9rghmjjv3tpvgxv2cq5eyj7smgjfkt2kh3gsuemd0r7ptkpypvrg8ekk9vyu2uxczsj9rw2h689s3vnpuhymqs7kztpxqchdyut5fmk9sjwrzghwhwauwr9ckf8qkp4mh2f9kfgw7jhfmawwynx7gsduts38chvgca4cg0uusnequvrsn92zw7ky0m8ycmmgu88g8velvkp8xl3w2n8ds6vkqutnyffqxf09snuehvff4wzxn4h2q5empzg6akyvm4y62geavzppkv9q2m2xmj42dea39ydpngxhch4e4vn0eu7kx0dwevzc5kx9djj6yfvs8cspgj07qp9wyqytw6852cg0e3qs43rqyraacj4gvvxavdwrhlg223xjck2muhz4q94uwh2qzdyku2xfy6gncj47xf4ypswpunv4gdj5ar63rvv5ksy3ngwkukz4kyve8pp6v52wk6tchx4jwjy0yzkwv83gz9xcuuq437e7vd4m2sgz3phpk9yjq57e7j56ksznjgrmadzz82xef48r2k548d52zgqkk8psu5pcjj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T06:10:00Z"
  mac: ENC[AES256_GCM,data:nlQ2wLFzaJsYEjArXJu2aXaCJejS0BtStWU/F8wfHGrEKbQxEOTPEi78+ln4wl0z0mciKz40i2BLj/8hS97AmViNUZHqURy7HKhKIlq4JjKsb8ncruduvBQ3qZsy/mfN3k/Tf+pjPehzvZnM31NK/fbkQInFk4vvQi9YAvqmTVI=,iv:QOOJPFQgwopxZY95pkcCJofRqLEzNigSoaKwutB2d7g=,tag:gXTyA6nO0169iltCz6EHyg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
