apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0wYqwuemouhhTnjkTnoVEhRhlk9pwFbv2kysGkil6r9H0WW9AHmDQcuuhVYuxlXPwi+XPB8=,iv:XYxIuFdy53a3qbhT47SWjHKZ7i9ucazpT2KDjaa6yfk=,tag:GdWgf8YrN0k9SEja2Avd7w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHJoNThTdUVB
        bjhtektUa3hoUjQxeldjVENBMk9mRExKMGc3dXBiekJBK1QvV2lnNHJVNTkxOTJO
        cVRxc0JURk9QZG1EUmk5RXRtWm9GYjlnWGt0OXBSTGtpVTloenBFVE1wOWpwdE1T
        VlpkYkcrdlUvclZsYU5RNUJ2Ymsxc0VRRnlXSENPTEhNdmlFZFNFalZYcWpXWEFq
        aEN1QThKTmxSZG9yQ3pDbWgzRUI2WndTY0VNV2xHS1RpMkN1dEZQaXVIb0JzK05E
        M09uVFB4ejBqS3dRNGlkR2xtNkpyUmQvQzRPSkJIWHI2bUNlcFZxeEF2NnJ0NGQ0
        SzJUMkNpZGdYM1JISGpMNDVwcDIwVVlqQ1RxYVpGazlvMXlIOFhEbzh3b2EzbFRl
        aEYzd0RVYnZ6WDFvSVRhc1J2bUJibXI1eXJsYlYzSnhTZlhjWWdlWHhDQzcxd3pW
        ajdCVG41Y0VrSUJjS0N0WTJOaDZraDFmdlY5UW9HZ29jREFRdmlpU2IrQ3FrZkIx
        SXFndThvMnF1VFJ0RWpEQjcyRjR2RUMyZWY0VzdxOWR0Q1NlQldvWmFGT0d4ZGt2
        a2MzQzJWbzdhNHBEZEkwb1VCY2VuK2Z4bGx2K0dWeWx0b0lGUnpLcmVIaFN5cEk5
        dm5MWHBkL3FkNE5vd05MZy90YTUzMnY0ZWNTMWtjRFhQcExLbUF6aGhCR25vbzUv
        ak1FbkMwT1RsNmJqQnRMQSs5SktpaXo1Y1JZYkVDMk5vcHhicVZWWTRORTJrajUy
        TlZQL2htbGNiWVloNHozOHRIM1EyOGUvZXU5Vytka3VHMFdwY2xjalRFcTg0T1lF
        WjZxemN6Y0lPSVRFcExqaDVvVUplRFNaUnE0VzJnWnVJc0RZN1NGMEtXemxFeGdZ
        VDAwRlYrSzNMcTRUMmY3dkxJT1FaRlEvZGltL3dvM1owd01ZQWo5bnpHbkFDc0dr
        MitwNkNweTBHMHlPdU9SS1dseVpaZURmVk1qdWRsZm5uUllIYmZwSXh1MDZOUUZy
        SFJFdkJsZ21udklvbmQvd0E3OGlZZzQ0MERQOXNEVXB5M0hFaklFa2JORkRyNDRo
        ZlZkbnpvcTFaRFAwbVZKYi8wbnp0UTQzZkRwTktya2lwZGk2TmdZbmtsL0p2MTk3
        N2tMUWZ6bDMyalFoKzNVeEhRSVljdHd0NFgzQkgxOFY0RDdlWDhGbllZTEFtK21Z
        M1NhSTlDWGpicm9vbGtMNFhKZG5vWDdnNStGQTAwQ2s5K09IbEM4dTZyRVo3cm1R
        U2NNemZSemV4ekxWUmRYQlJsci91c2RpeC9mTktOZURRR3o5MDZRN09qZWJlV3Az
        WFpOZ0JEenJNK2J5c1RmNXJFeUZ0YXRGTmpiUUFnYW1CbUUzditkT1lidmZKZnNu
        N0h2YnhvQTc0WmdIZkdkcFZPbjErNE1SVTQvenp4ZzJrd2NZSHVENThKblh1YnRQ
        NmVNR1dhR0JidVZRSEhybWRiSkRRTFE1cTRZQ1MreUt4djFwSWt2RlpQd21VSW9F
        bG9EWFU5NUtITDZvT0xDeFo4QW9zMWJxRXk0ZTViTXkyUzFNUE51eWtYUE5scGZU
        Y2FUREtCNWZlR1B4Mnc2MWh5NTJ6cEFPTzFMSlNuY21tSUlSMXJsWk40cU9uVng1
        THY0dWF3ZmFUNEljeDM0aUM1eVZTRTErTVd2Qklod1doUWFTWGhIUCt0QjVyMjdu
        RkV4NnZSOHdaNzVKa2xYc24zd290RkJCWUdkL0tyUmFoOTRqMEpBM1lPcUF5aEd0
        T0VQOW5UcmptWEZmNmIvNDBkSzErNHNUeEtTR0FjekZHMGhDWkovOFVOTm0wcTh4
        dlMxWURscDY3cUk4NXl5dyttUkZaNGdqNE00V1RYNWlFVGM2dzhwWFRUQTRjcVNY
        TUsrdmViUmdEc3NuNVQ4TWlNRlRsaEZybkREY2pDemlMVGFaaVBTbEJIVkhFZwpZ
        M0lwUDlRRGlKbDZSNk8zcFJFbnQveGk0Y09QQXI0elBmcmo1N0NHaHRZCi0tLSBx
        NS9Ta2dzMFc2VWtlcDliUkp0TjFEb2trWEt1Uyt0aW00ZVBTVDNPMDVNCiw6tLe+
        6360HQaFi+t/k7CPbogcRqWWbCexcwG6xwCPlwgYR/g2dI2B6l5UVd9tCk9/htxE
        6YA5UVFpdjrgErI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z2790e0enqwlpxt5q5mrgd59tx92fqfpeltynww0v46tmyd0jxup9x53j087q7vtc3zuhzdxp94hxthxnfd7rtdl2uz2d6jwwdueknvcfesczsmexd2cmgfet2ypxplsgxlzy6rgf3rzlx3907qrfl3sk4lexu4rs496hyms0vn5x624xycyqh08uj73kwq2vqxz5a6cpy02ssrtzfxwuzey5kuy4pzekrk2r92pvwmes2rgf8fnls4njw5hrx4a8x99tg58vm5j4zfux4a2vr9q0yaj72g2t4rhc0vv3g4z52842a782ppu50gyqwet0xsr9g2s8ny0zqjvmz5p9vp2wtnuexnkvg5tl4e9v3ep45gr6q0ryh03uvsvnz7dr4ftjmk42k2gwc22esyjvg4dg9uv6sx4cyjthwk7zx5y8aehnk9pvmn3yyygvx2d99vynvvra0gtal02y3axnfpxvxhsjg94sy58kld5yuggzw9s9j07gpj0au5utsv4c34yj6yp5pl3j4sc0g4z50ngp7xajxdjt9jytda3yc2un6qrrd3hvsypxag987e76tktgqqjfd23gwu0xzc6extlqv9faqa2vzn72m8xs9hvn6qhm9sxhpkmv65wwa4quu4jwnp6sf7vakavw4z2kgxp2j55glprp29j8v0uhyftsx30n3ejxd2g409zyt9xh4jnw2jc20qms4z6l4v3eflqnxqs8n5x3vc6dcv590kpnx36tythvsutuqfqqqxt8mjngcwfr34k22nw5fuhw7may4akketqplcu0vdd7xeetz2cyqe3mf4g4aktk36tzxmx2fu27s4ttrh4yd4g5szsj2wz5wtk8d3g47y9p6kaxzmwkgum74jwtqn929j4w4lhhxmx6pudcv340fskyxart475dpcl2ypw20qu59yz50c85da35qwstz7fnkqqm6g62qmc48v4wkj2jflpaqvt5g5ymuasxuyanjeqygryz6kvajajdgftdrxcv7aly2d08urxfaeg5rnz5gjcqgjmwkzzvw5x3uj5c5p64w98k86sz4m6us30py4tn0cxh6q9gcwxz4vuuzy32lmxr029qpmn2f0a4fzfq94edt96765s8fy0quq55zy0gu5yme9hxz5ze2rlga4fgkx0kpng2rgjj0yktfxf5pw5qq9vjf24twgm2vyg5zhk2gqu808q8ep5ne99xs9rjezutn6czxahqusscwypfs5n56ydcngq29dlg0p675qcmkpt062vccauw6dudhr0522q9lahhyz5jmlt5guq8sm7g6c5u2pmtu6502umzxfk0fd06g95zrqhgjf8e2gvwcx8q5ty4ds4phhkff6ek9xs7xxp4aqtlc9rghmjjv3tpvgxv2cq5eyj7smgjfkt2kh3gsuemd0r7ptkpypvrg8ekk9vyu2uxczsj9rw2h689s3vnpuhymqs7kztpxqchdyut5fmk9sjwrzghwhwauwr9ckf8qkp4mh2f9kfgw7jhfmawwynx7gsduts38chvgca4cg0uusnequvrsn92zw7ky0m8ycmmgu88g8velvkp8xl3w2n8ds6vkqutnyffqxf09snuehvff4wzxn4h2q5empzg6akyvm4y62geavzppkv9q2m2xmj42dea39ydpngxhch4e4vn0eu7kx0dwevzc5kx9djj6yfvs8cspgj07qp9wyqytw6852cg0e3qs43rqyraacj4gvvxavdwrhlg223xjck2muhz4q94uwh2qzdyku2xfy6gncj47xf4ypswpunv4gdj5ar63rvv5ksy3ngwkukz4kyve8pp6v52wk6tchx4jwjy0yzkwv83gz9xcuuq437e7vd4m2sgz3phpk9yjq57e7j56ksznjgrmadzz82xef48r2k548d52zgqkk8psu5pcjj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T05:42:02Z"
  mac: ENC[AES256_GCM,data:eaVQHmB/IU18ymZKiNGKpQoA9RemCSlod2NV9ktb4sq0sb5lNhxtG8JzoxxYYaM1DCCWvbpPYXvkR/QZKeP8vSGOeeVHERoSIuji7iMOVZ43FfhmAdjTD4RZkBVQGsp2DGS9bwiQ8urSx4IgqkZcEiUQO2VMnDDEkyte5lREjUs=,iv:KBQ0Ym2z3073QKoLCijTWuQf2/QaaWcE9+/gkSsAvik=,tag:cuie/GEhmjd04p77NRelMw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
