apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ymux8sQPR17k6tm5xDB46uSWjBoX5TDaY5a3pTNZCKPWgzEcUHt19AF/SKbC887/l518NFU=,iv:92Vxus3eYiFGc98WGUvtxdc65TPFSZz61fRiLvTvdEs=,tag:Kl4DhNARE22vmDPxJ+zuiA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHdpa2lOOU9y
        RnIvTWJiV0QrYTZyWjNmZjloRWZ4SnZvajRjRW4zaVhma2Z6SUlqajlZUzBNcTFp
        bXdOci9saVJpc2dyV1grWTZaNG1aeGl1eG5GYTRONjMrRzlXVWpGS25pWFcyZlQ0
        dm1HTlczdkxhYUcxbis3SHRXcWg0OFJZTFh1N00vNS93c1pFRVFWdFRTWit1S08x
        eU80N05PZ1ZmSHIzcDhkeFkwSVVmb3hPSmg1NFIvcGtacnVYNTFHN0JtU2UvOXlh
        UDZmd3JSR0V6aFZ5TVg2Vy9IRmdIRmtHODJCK3VHNCtxeGlhd0c4YklvQ1hvV1Ax
        bXBWK3ZDWElDVXRLOXhmVWpVTDR6UlNPbUZFODh6dGNtVmttRlpmR2M1N3ZYcTQ4
        d1EyZFludzNLUVNQUEJtKytRK0d3b2VDaGE2aStvTlZCbWcwU1JPeEF5QXVPRkwy
        MjErazBmc09oV2ViVHBUSGllQ0F5R1F4L2J2MHdSNjFXSW14cFNGRTRFcDErSGVH
        YTE2QzVaZW1VOE9adVNIUGVZRy9iZ3ZWT2FzMGhFSXhmTG1FaU9NMHlVazJ5WkpB
        S2d2Y3IxZkxQTWd1MjlKcWQrU2lhRHYvMmhuVFZRSDRza09XZWRYem1yR3JtUVpi
        VDFOM0Y0b2FwTzF0eGxHR0NKQWlFMmJXVjVWVXQ5S3E2TjNZUjhUQUtlb0ZxMHJh
        blZvV0NPcEt5YkZYRFY5dWw4WDBSSEtIU1poUWR5dVhYK1ozZGt3ZjQvbUZzZC9u
        eGNzOGxYV2FUaVBXQStEVTcrTkUvTEFzZEhuT3d5c3V1emlFcWQvUHo3WEdQbG9S
        djQ4YUxML2hLd2NGVEhTdGxZU2J5WWZQNDZqejJkeDVkcVRZM0ZMMFlPNTFGdjJD
        ajdUZHY3MkxQbFdSMVRxZjF4UmkvTXl6bTdnVklLWWlSa0FaNnFUMWd0U1lTc0RB
        SXZ4Ung3bmFFaStienhOMEkrbXJTUlh3SkgxcEJDV2M4QnA5bDlzZzlwam13ZEZo
        Nm5Va0JidC85R3REUW9YSUlJa3BPVk5OeE9lSDNjTit6REhIcjJvVFMvZEkwdTZO
        U3BwTC9YMnduR2dGZEk1R1pRbWhJWHBYSmJEYUZwZjRhZkcrSVJDUmxiUzI4RFJw
        ZzNweFpjZFdUMTFtN3plcTAzMXdxK09Sa0FhbE8vQ0xBQ1Jud25tK3A4TURMOXBx
        K0d0Z1dSMHQ3dDZsZHJXc0I3bVBkREZSa1JFbHczand1WDVaN1BKTmkzSG1QcDVE
        ZUtQZE5NSDZ1Y28yOWJTT0FIYmhUdUpZbzhZWVlqdHZpaG5QVHhJNDQvazlSRUli
        MXBVQWlCaFpiWkthWERveVo3WkZoRlNKWlR3cUtLSDFDOXRrRFFrR0JIZUdIdXhW
        YlR2cmRNaDgwUU9xZFQxajFMQXN6OGVYSkZkanRqZVpYRXhUL1B3OEwyZEE3dTND
        VFRtaG5TNlduYWovT3JzNzkyWG1zQm80MjdjQUdldHBBZDRRUzkyUE9VbEllTnd4
        UWV6SG8xdjl3UWxNLzh3bDEzRGlkNUl4Zk1NSGw3SW5aVTNidXRFRlUyTW9sSzlJ
        bCtHa1djeHppc25wb2huWWVSM3BRQWUxTEdHWkZFSmhQMzVadDUvMi9NdnNVa2Zm
        dFJnNUJoZWd3TXVuRFlDUjNxQSt6MVlJQ21VcUIrbUswY2dDemFmN2tqaUY1eUpi
        NkU5OXZiUWJpWWtqRmN0N3BZQkJOS1k5ZGRrMTVORUtUMUZDODlKQ0dvWGRBamtr
        ajFFS3gzOVg2KzJkYWFzdHdzRmxZYUNGdGYzY1I4OEdxTE9KZGVlZ2NGK2UxTStk
        aVM2d0FZaHdyVTNhQmpMOUYwZWQ5K0FqWHZia3hQY2p6QkFPakhsZEVJMU93aERj
        Tkc4YzVubGdpN3NVenJVZzF4Z2FaNi82SDFLTG1XZHNWZnlRUTFZWndvZ1JWdwpI
        aExTUSs3VmN5N1hsSUZNRThXWHBtbmsrdW1qcTVYTWFyeXZ5QmpaTTZ3Ci0tLSBD
        T2o0SlRYT0F5Z3QxUUhnQWVPUHBzNXYzUXRodlhFMzN5SFRiTWlBandZCm8dGR4G
        Ny9oPFIPDimosGTN2l3kdSWNAW/35HlSgrLzOuGozQK/hJtml0pSzd6SGd/nItQ5
        SFPP9V0od6gZohA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z2790e0enqwlpxt5q5mrgd59tx92fqfpeltynww0v46tmyd0jxup9x53j087q7vtc3zuhzdxp94hxthxnfd7rtdl2uz2d6jwwdueknvcfesczsmexd2cmgfet2ypxplsgxlzy6rgf3rzlx3907qrfl3sk4lexu4rs496hyms0vn5x624xycyqh08uj73kwq2vqxz5a6cpy02ssrtzfxwuzey5kuy4pzekrk2r92pvwmes2rgf8fnls4njw5hrx4a8x99tg58vm5j4zfux4a2vr9q0yaj72g2t4rhc0vv3g4z52842a782ppu50gyqwet0xsr9g2s8ny0zqjvmz5p9vp2wtnuexnkvg5tl4e9v3ep45gr6q0ryh03uvsvnz7dr4ftjmk42k2gwc22esyjvg4dg9uv6sx4cyjthwk7zx5y8aehnk9pvmn3yyygvx2d99vynvvra0gtal02y3axnfpxvxhsjg94sy58kld5yuggzw9s9j07gpj0au5utsv4c34yj6yp5pl3j4sc0g4z50ngp7xajxdjt9jytda3yc2un6qrrd3hvsypxag987e76tktgqqjfd23gwu0xzc6extlqv9faqa2vzn72m8xs9hvn6qhm9sxhpkmv65wwa4quu4jwnp6sf7vakavw4z2kgxp2j55glprp29j8v0uhyftsx30n3ejxd2g409zyt9xh4jnw2jc20qms4z6l4v3eflqnxqs8n5x3vc6dcv590kpnx36tythvsutuqfqqqxt8mjngcwfr34k22nw5fuhw7may4akketqplcu0vdd7xeetz2cyqe3mf4g4aktk36tzxmx2fu27s4ttrh4yd4g5szsj2wz5wtk8d3g47y9p6kaxzmwkgum74jwtqn929j4w4lhhxmx6pudcv340fskyxart475dpcl2ypw20qu59yz50c85da35qwstz7fnkqqm6g62qmc48v4wkj2jflpaqvt5g5ymuasxuyanjeqygryz6kvajajdgftdrxcv7aly2d08urxfaeg5rnz5gjcqgjmwkzzvw5x3uj5c5p64w98k86sz4m6us30py4tn0cxh6q9gcwxz4vuuzy32lmxr029qpmn2f0a4fzfq94edt96765s8fy0quq55zy0gu5yme9hxz5ze2rlga4fgkx0kpng2rgjj0yktfxf5pw5qq9vjf24twgm2vyg5zhk2gqu808q8ep5ne99xs9rjezutn6czxahqusscwypfs5n56ydcngq29dlg0p675qcmkpt062vccauw6dudhr0522q9lahhyz5jmlt5guq8sm7g6c5u2pmtu6502umzxfk0fd06g95zrqhgjf8e2gvwcx8q5ty4ds4phhkff6ek9xs7xxp4aqtlc9rghmjjv3tpvgxv2cq5eyj7smgjfkt2kh3gsuemd0r7ptkpypvrg8ekk9vyu2uxczsj9rw2h689s3vnpuhymqs7kztpxqchdyut5fmk9sjwrzghwhwauwr9ckf8qkp4mh2f9kfgw7jhfmawwynx7gsduts38chvgca4cg0uusnequvrsn92zw7ky0m8ycmmgu88g8velvkp8xl3w2n8ds6vkqutnyffqxf09snuehvff4wzxn4h2q5empzg6akyvm4y62geavzppkv9q2m2xmj42dea39ydpngxhch4e4vn0eu7kx0dwevzc5kx9djj6yfvs8cspgj07qp9wyqytw6852cg0e3qs43rqyraacj4gvvxavdwrhlg223xjck2muhz4q94uwh2qzdyku2xfy6gncj47xf4ypswpunv4gdj5ar63rvv5ksy3ngwkukz4kyve8pp6v52wk6tchx4jwjy0yzkwv83gz9xcuuq437e7vd4m2sgz3phpk9yjq57e7j56ksznjgrmadzz82xef48r2k548d52zgqkk8psu5pcjj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T06:10:00Z"
  mac: ENC[AES256_GCM,data:++T/Zoa5mf4WSRhvLUWpslgAycdhg6ALEl6+Q4ZeEhY7OO5nHoJ5S302d8q31dQVHWmCIZbgeOzFHpqPCqiHnXhiMd9jpGBvg41QU6a47eVd9NT4Ai2ytN4vXLMkJtPGhoJidN/F4RgorLUpTQfKC9BRBW23BUdE0efAc4puvYc=,iv:iYwHCVPj+9OVoN1XJAu9+McfKyqfbj9YQ8+iTzERTlI=,tag:UU5nlDxf+uaGc/MFcUlW4Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
