---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.20:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.20"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "kube-hp-node1"
    ipAddress: "192.168.1.188"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4b3cd373a192c8469e859b7a0cfbed3ecc3577c4a2d346a37b0aeff9cd17cdb0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "b0:5c:da:30:69:57"
        dhcp: false
        addresses:
          - "192.168.1.188/24"
        routes:
          - gateway: "192.168.1.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.1.20"
  - hostname: "kube-hp-node2"
    ipAddress: "192.168.1.189"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4b3cd373a192c8469e859b7a0cfbed3ecc3577c4a2d346a37b0aeff9cd17cdb0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "b0:5c:da:31:48:49"
        dhcp: false
        addresses:
          - "192.168.1.189/24"
        routes:
          - gateway: "192.168.1.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.1.20"
  - hostname: "kube-hp-node3"
    ipAddress: "192.168.1.190"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4b3cd373a192c8469e859b7a0cfbed3ecc3577c4a2d346a37b0aeff9cd17cdb0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "f8:b4:6a:ac:d2:c3"
        dhcp: false
        addresses:
          - "192.168.1.190/24"
        routes:
          - gateway: "192.168.1.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.1.20"
  - hostname: "kube-hp-node4"
    ipAddress: "192.168.1.191"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4b3cd373a192c8469e859b7a0cfbed3ecc3577c4a2d346a37b0aeff9cd17cdb0
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "b0:5c:da:30:e8:49"
        dhcp: false
        addresses:
          - "192.168.1.191/24"
        routes:
          - gateway: "192.168.1.1"
            network: 0.0.0.0/0
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

